'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const {createGame}=require('./harness.cjs');
const root=path.resolve(__dirname,'..');
test('malformed and blocked storage still allow starting and retrying a run',()=>{for(const options of [{storage:{neonshinobi_v2:'{broken'}},{denied:true}]){const g=createGame({...options,ui:true});g.run("NSCampaign.newRun('arcade');P.inv=0;hurtPlayer(10,1);NSCampaign.resume()");assert.equal(g.read('mode'),'playing');assert.ok(g.read('NSStore.data.checkpoint'));if(options.denied)assert.equal(g.read('NSStore.available'),false);}});
test('legacy best scores are imported, invalid and infinite values are rejected',()=>{assert.equal(createGame({storage:{neonshinobi_best:'830'}}).read('NSStore.data.best'),830);for(const value of ['NaN','Infinity','-10','hello'])assert.equal(createGame({storage:{neonshinobi_best:value}}).read('NSStore.data.best'),0);});
test('versioned saves validate district, difficulty, upgrades, numeric limits and settings',()=>{const g=createGame({storage:{neonshinobi_v2:JSON.stringify({version:2,settings:{sound:'false',volume:20,reducedMotion:true},checkpoint:{version:2,district:99,difficulty:'arcade'}})}});assert.equal(g.read('NSStore.settings.sound'),true);assert.equal(g.read('NSStore.settings.volume'),1);assert.equal(g.read('NSStore.data.checkpoint'),null);assert.equal(g.read("NSStore.validateCheckpoint({version:1,district:0,difficulty:'arcade'})"),null);assert.equal(g.read("NSStore.validateCheckpoint({version:2,district:0,difficulty:'__proto__'})"),null);assert.deepEqual(g.read("NSStore.validateCheckpoint({version:2,district:0,difficulty:'arcade',upgrades:{blade:900,mobility:-10},hp:999,score:Infinity}).upgrades"),{blade:3,mobility:0,vitality:0,flow:0});});
test('checkpoint survives a full page reload with upgrade and prior district progress',()=>{const g=createGame();g.run("NSCampaign.newRun('ronin');NSCampaign.state.district=3;NSCampaign.state.upgrades.flow=2;score=1300;NSCampaign.checkpoint()");const next=createGame({storage:Object.fromEntries(g.persisted)});next.run('NSCampaign.resume()');assert.equal(next.read('NSCampaign.state.district'),3);assert.equal(next.read('NSCampaign.state.upgrades.flow'),2);assert.equal(next.read('score'),1300);assert.equal(next.read('P.maxhp'),4);});
test('records are bounded, deduplicate retries and keep the highest score',()=>{const g=createGame();g.run("for(let i=0;i<15;i++)NSStore.record({id:'run'+i,score:i*100,difficulty:'arcade',district:1,won:false,time:2,cycle:0});NSStore.record({id:'run14',score:999,difficulty:'arcade',district:1,won:false,time:2,cycle:0})");assert.equal(g.read('NSStore.data.runs.length'),10);assert.equal(g.read('NSStore.data.best'),1400);assert.equal(g.read('NSStore.data.runs[0].score'),1400);});
test('help freezes combat and closing it requires an explicit resume',()=>{const g=createGame({ui:true});g.run("NSCampaign.newRun('arcade');NSUI.openHelp()");assert.equal(g.read('mode'),'paused');assert.equal(g.elements.get('modal').open,true);g.step(3);assert.equal(g.read('NSCampaign.state.stats.time'),0);g.elements.get('modal').close();assert.equal(g.read('mode'),'paused');g.elements.get('resumeRun').click();assert.equal(g.read('mode'),'playing');});
test('repeated pause / resume and menu navigation never create another RAF loop',()=>{const g=createGame({ui:true}),before=g.raf;g.run("NSCampaign.newRun('arcade');for(let i=0;i<5;i++){NSUI.pause();NSUI.unpause();}NSUI.pause();NSUI.title()");assert.equal(g.read('mode'),'title');assert.equal(g.raf,before);assert.ok(g.elements.get('continueRun'));});
test('confirming a new campaign replaces the old checkpoint only on confirmation',()=>{const g=createGame({ui:true});g.run("NSCampaign.newRun('arcade');NSCampaign.state.district=2;NSCampaign.checkpoint();NSUI.title()");const id=g.read('NSStore.data.checkpoint.runId');g.elements.get('newRun').click();assert.equal(g.read('NSStore.data.checkpoint.runId'),id);g.elements.get('cancelNew').click();assert.equal(g.read('NSStore.data.checkpoint.district'),2);g.elements.get('newRun').click();g.elements.get('confirmNew').click();assert.equal(g.read('NSCampaign.state.district'),0);assert.notEqual(g.read('NSStore.data.checkpoint.runId'),id);});
test('settings persist and reduced motion suppresses full-screen flashes',()=>{const g=createGame({ui:true});g.run("NSStore.setSetting('reducedMotion',true);NSStore.setSetting('sound',false);flashEl.style.opacity=0;whiteFlash(.8)");assert.equal(g.read('flashEl.style.opacity'),0);const next=createGame({storage:Object.fromEntries(g.persisted),ui:true});assert.equal(next.read('NSStore.settings.sound'),false);assert.equal(next.document.body.classList.contains('reduced-motion'),true);});
test('standard gamepad neutral gating, simultaneous sources and disconnect pause work',()=>{const g=createGame({ui:true});g.run("NSCampaign.newRun('arcade')");const pad={index:0,connected:true,mapping:'standard',axes:[0,0],buttons:Array.from({length:17},()=>({pressed:false}))};g.setPads([pad]);g.run('NSControls.poll()');pad.buttons[1].pressed=true;g.run('NSControls.poll()');assert.equal(g.read('keys.TA'),true);g.run("NSControls.setInput('TA',true,'pointer:2')");pad.buttons[1].pressed=false;g.run('NSControls.poll()');assert.equal(g.read('keys.TA'),true);g.setPads([]);g.run('NSControls.poll()');assert.equal(g.read('mode'),'paused');assert.equal(g.read('keys.TA'),false);});
function worker(){const listeners={},buckets=new Map(),deleted=[];const scope='https://example.com/arcade/games/neon-shinobi/';const bucket=key=>{if(!buckets.has(key))buckets.set(key,new Map());const data=buckets.get(key);return{addAll:async urls=>{for(const request of urls){assert.equal(request.cache,'reload');const url=request.url;data.set(url,new Response('cached:'+url));}},match:async request=>data.get(typeof request==='string'?request:request.url)?.clone()};};const self={registration:{scope},clients:{claim:async()=>{}},addEventListener:(type,fn)=>listeners[type]=fn};const caches={open:async key=>bucket(key),keys:async()=>[...buckets.keys()],delete:async key=>{deleted.push(key);return buckets.delete(key);}};vm.runInNewContext(fs.readFileSync(path.join(root,'sw.js'),'utf8'),{self,caches,URL,Request,fetch:async()=>{throw Error('offline');}});return{listeners,buckets,deleted,bucket,scope};}
test('offline shell and each versioned game module are cached together',async()=>{const w=worker();let pending;w.listeners.install({waitUntil:p=>pending=p});await pending;for(const [suffix,mode] of [['','navigate'],['index.html?source=install','navigate'],['js/campaign.js?v=2.0.2','cors'],['css/game.css?v=2.0.2','cors']]){w.listeners.fetch({request:{method:'GET',url:w.scope+suffix,mode},respondWith:p=>pending=p});assert.match(await(await pending).text(),/^cached:/);}});
test('service worker never intercepts or deletes another game installation',async()=>{const w=worker();w.bucket('other-game');w.bucket('neon-shinobi:'+encodeURIComponent('/another/')+':1');const own='neon-shinobi:'+encodeURIComponent('/arcade/games/neon-shinobi/')+':1';w.bucket(own);let pending;w.listeners.activate({waitUntil:p=>pending=p});await pending;assert.deepEqual(w.deleted,[own]);let intercepted=false;w.listeners.fetch({request:{method:'GET',url:'https://example.com/arcade/games/other/index.html'},respondWith:()=>intercepted=true});assert.equal(intercepted,false);});
test('all local entry assets and install icons exist; manifest scope stays inside this game',()=>{const html=fs.readFileSync(path.join(root,'index.html'),'utf8');for(const match of html.matchAll(/(?:src|href)="(\.\/[^"?]+)(?:\?[^\"]*)?"/g))assert.ok(fs.existsSync(path.join(root,match[1])),match[1]);const manifest=JSON.parse(fs.readFileSync(path.join(root,'manifest.webmanifest'),'utf8'));assert.equal(manifest.scope,'./');for(const icon of manifest.icons)assert.ok(fs.existsSync(path.join(root,icon.src)));});
