/* Run with Node + Playwright. Set BROWSER_EXECUTABLE for a local Chromium,
   EMOJI_BASE for the deployed game. Tests write only browser-local saves. */
const {chromium}=require('playwright');
const assert=require('node:assert/strict'),http=require('node:http'),fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'../../..'),out=path.resolve(__dirname,'../evidence');
fs.mkdirSync(out,{recursive:true});
const results=[],errors=[];
const check=(name,ok=true)=>{assert.ok(ok,name);results.push(name);console.log('PASS',name)};
(async()=>{
 let server,base=process.env.EMOJI_BASE;
 if(!base){server=http.createServer((req,res)=>{let file=path.join(root,decodeURIComponent(req.url.split('?')[0]));if(file.endsWith('/'))file+='index.html';res.setHeader('Content-Type',file.endsWith('.mjs')?'text/javascript':file.endsWith('.css')?'text/css':'text/html');try{res.end(fs.readFileSync(file))}catch{res.statusCode=404;res.end('Not found')}});await new Promise(r=>server.listen(0,'127.0.0.1',r));base=`http://127.0.0.1:${server.address().port}/games/emoji-shift/`}
 const browser=await chromium.launch({headless:true,...(process.env.BROWSER_EXECUTABLE?{executablePath:process.env.BROWSER_EXECUTABLE,args:['--no-sandbox','--disable-dev-shm-usage']}: {})});
 const {Game}=await import('../engine.mjs'),{bestMove}=await import('./playthrough.mjs');
 const contexts=[];
 async function newPage(options={}){const ctx=await browser.newContext({...options,reducedMotion:'reduce'});contexts.push(ctx);const p=await ctx.newPage();p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.status()>=400&&!r.url().endsWith('favicon.ico'))errors.push(r.status()+' '+r.url())});return p}
 const state=p=>p.evaluate(()=>{const s=JSON.parse(localStorage.getItem('emoji-shift-expansion-v1'));return s.sessions[s.lastMode]});
 async function tap(p,i,touch=false){const tile=p.locator(`[data-i="${i}"]`);if(touch)await tile.tap();else await tile.click();}
 async function turn(p,pair,touch=false){await tap(p,pair[0],touch);await tap(p,pair[1],touch);if(await p.locator('#combine').isVisible())await p.locator('#combine').click();await p.waitForFunction(()=>document.querySelector('#board').getAttribute('aria-busy')==='false')}
 try{
  const desktop=await newPage({viewport:{width:1440,height:1000}});await desktop.goto(base);await desktop.waitForSelector('.tile');check('Desktop loads all 49 vector signals',(await desktop.locator('.tile svg').count())===49);await desktop.screenshot({path:path.join(out,'desktop.png'),fullPage:true});
  let initial=await state(desktop),pair=Game.restore(initial).availableMoves()[0];await turn(desktop,pair);let after=await state(desktop);check('Tap controls spend exactly one shift',after.used===1);await desktop.reload();await desktop.waitForSelector('.tile');assert.deepEqual(await state(desktop),after);check('Reload resumes exact board and counters');
  await desktop.locator('[data-mode=daily]').click();let dailyInitial=await state(desktop);check('Daily tab is available without campaign unlocks',dailyInitial.mode==='daily');
  const twin=await newPage({viewport:{width:1280,height:900}});await twin.goto(base+'?mode=daily');await twin.waitForSelector('.tile');assert.deepEqual(await state(twin),dailyInitial);check('Independent clients receive identical Daily Shift');
  await turn(desktop,[22,23]);await turn(twin,[22,23]);assert.deepEqual(await state(desktop),await state(twin));check('Combination preview confirms once; refill streams stay identical');
  const dailyAfter=await state(desktop);await desktop.locator('[data-mode=campaign]').click();assert.deepEqual(await state(desktop),after);await desktop.locator('[data-mode=daily]').click();assert.deepEqual(await state(desktop),dailyAfter);check('Campaign and Daily save slots remain independent');
  await desktop.locator('#restart').click();await desktop.locator('#confirm-restart').click();assert.deepEqual(await state(desktop),dailyInitial);check('Daily retry restores identical puzzle');
  let g=Game.restore(await state(desktop));while(!g.over){const {pair}=bestMove(g);await turn(desktop,pair);g=Game.restore(await state(desktop))}
  check('Daily Challenge can be completed using UI controls',g.won);check('Win screen and share button appear',await desktop.locator('#share').isVisible());await desktop.context().grantPermissions(['clipboard-read','clipboard-write']);await desktop.locator('#share').click();check('Share result copies date, score, and game link',(await desktop.evaluate(()=>navigator.clipboard.readText())).includes('?mode=daily'));
  await desktop.locator('#close-result').click();await desktop.locator('[data-mode=free]').click();check('Free Play has unlimited shifts',(await state(desktop)).moves===null);const freeInitial=await state(desktop);pair=Game.restore(freeInitial).availableMoves()[0];await desktop.locator('#board').focus();
  await desktop.keyboard.press('Home'); // No custom Home behavior: navigate explicitly from center.
  let cursor=24;while(Math.floor(cursor/7)!==Math.floor(pair[0]/7)){const up=Math.floor(cursor/7)>Math.floor(pair[0]/7);await desktop.keyboard.press(up?'ArrowUp':'ArrowDown');cursor+=up?-7:7}while(cursor%7!==pair[0]%7){const left=cursor%7>pair[0]%7;await desktop.keyboard.press(left?'ArrowLeft':'ArrowRight');cursor+=left?-1:1}await desktop.keyboard.press('Enter');await desktop.keyboard.press(pair[1]-pair[0]===1?'ArrowRight':'ArrowDown');await desktop.keyboard.press('Enter');await desktop.waitForFunction(()=>document.querySelector('#board').getAttribute('aria-busy')==='false');check('Keyboard can complete a valid swap',(await state(desktop)).used===1);
  const mobile=await newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:1});await mobile.goto(base+'?mode=daily');await mobile.waitForSelector('.tile');await mobile.screenshot({path:path.join(out,'daily-mobile.png'),fullPage:true});check('390px mobile layout has no horizontal overflow',await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));check('Touch targets exceed 40px',await mobile.locator('.tile').first().evaluate(e=>e.getBoundingClientRect().width>=40));
  await turn(mobile,[22,23],true);check('Real touch taps trigger only one combination',(await state(mobile)).combos===1);
  const touchState=await state(mobile);pair=Game.restore(touchState).availableMoves().find(([a,b])=>!touchState.board[a].power||!touchState.board[b].power);await mobile.locator(`[data-i="${pair[0]}"]`).scrollIntoViewIfNeeded();const a=await mobile.locator(`[data-i="${pair[0]}"]`).boundingBox(),b=await mobile.locator(`[data-i="${pair[1]}"]`).boundingBox(),cdp=await mobile.context().newCDPSession(mobile);
  await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:a.x+a.width/2,y:a.y+a.height/2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:b.x+b.width/2,y:b.y+b.height/2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await mobile.waitForFunction(()=>document.querySelector('#board').getAttribute('aria-busy')==='false');check('Touch swipe consumes one move without ghost click',(await state(mobile)).used===touchState.used+1);
  await mobile.reload();await mobile.waitForSelector('.tile');check('Touch game survives reload',(await state(mobile)).used===touchState.used+1);
  const narrow=await newPage({viewport:{width:320,height:740},isMobile:true,hasTouch:true});await narrow.goto(base);await narrow.waitForSelector('.tile');check('320px layout has no horizontal overflow',await narrow.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await narrow.locator('#help').click();check('Power guide opens accessibly',await narrow.locator('dialog').evaluate(d=>d.open));await narrow.locator('#close-help').click();
  const legacy=await newPage({viewport:{width:430,height:932},isMobile:true,hasTouch:true});await legacy.goto(base);await legacy.evaluate(()=>{localStorage.removeItem('emoji-shift-expansion-v1');localStorage.setItem('emoji-shift-runs-v02',JSON.stringify({unlocked:24,selected:24,best:56000,complete:[0,24]}))});await legacy.reload();await legacy.waitForSelector('.tile');await legacy.locator('#runs').click();check('Legacy completion unlocks run 26',await legacy.locator('[data-run="25"]').isEnabled());check('Run 27 stays gated until completion',await legacy.locator('[data-run="26"]').isDisabled());await legacy.locator('[data-run="25"]').click();check('New conveyor chapter loads',await legacy.locator('#mechanic').isVisible());await legacy.screenshot({path:path.join(out,'foundry-mobile.png'),fullPage:true});
  const interrupted=await newPage({viewport:{width:390,height:844}});await interrupted.emulateMedia({reducedMotion:'no-preference'});await interrupted.goto(base+'?mode=daily');await interrupted.waitForSelector('.tile');await tap(interrupted,22);await tap(interrupted,23);await interrupted.locator('#combine').click();const committed=await state(interrupted);await interrupted.reload();await interrupted.waitForSelector('.tile');assert.deepEqual(await state(interrupted),committed);check('Reload during animations restores the complete settled turn');
  check('No JavaScript errors or failed game resources',errors.length===0);
  fs.writeFileSync(path.join(out,process.env.EMOJI_BASE?'live-browser-results.json':'browser-results.json'),JSON.stringify({passed:results.length,checks:results,errors,url:base,date:new Date().toISOString()},null,2)+'\n');
 }finally{await browser.close();if(server)server.close()}
})().catch(e=>{console.error(e);process.exitCode=1});
