import test from 'node:test';
import assert from 'node:assert/strict';
import {Game,matches,expandHits,comboInfo,TYPES} from '../engine.mjs';
import {RUNS,dayKey} from '../levels.mjs';
import {loadProfile,recordResult,LEGACY_KEY,SAVE_KEY} from '../storage.mjs';
const tile=(face='😀',power=null,glitch=false)=>({face,power,glitch});
const stable=()=>Array.from({length:49},(_,i)=>tile(TYPES[(Math.floor(i/7)*2+i%7)%6]));
const multiset=board=>board.map(t=>JSON.stringify(t)).sort();

test('30 runs retain original opening and finale; five conveyor expansion runs',()=>{assert.equal(RUNS.length,30);assert.equal(RUNS[0].name,'WARM SIGNAL');assert.equal(RUNS[24].name,'AURORA RESET');assert.ok(RUNS.slice(25).every(r=>r.conveyor));assert.ok(RUNS[29].finale)});
test('invalid swaps consume neither move nor random sequence',()=>{const g=new Game({seed:43});let found=false;for(let i=0;i<6;i++){const before=g.snapshot();const r=g.play(i,i+1);if(!r.valid){assert.deepEqual(g.snapshot(),before);found=true;break}}assert.ok(found);assert.equal(g.play(6,7).valid,false)});
test('match patterns forge surge, burst, prism at the moved cell',()=>{
  for(const [cells,power]of [[[21,22,23,24],'surge'],[[21,22,23,24,25],'prism'],[[15,22,29,21,23],'burst']]){const b=stable();for(const i of cells)b[i]=tile('🔥');assert.equal(matches(b,22).powers.get(22),power)}
});
test('powers hit by a blast recursively activate, even at corners',()=>{
  const b=stable();b[24].power='surge';b[21].power='burst';b[14].power='prism';b[0].face=b[14].face;const {hits,activated}=expandHits(b,[24]);assert.ok(activated.includes(21));assert.ok(activated.includes(14));assert.ok(hits.includes(0));assert.equal(new Set(hits).size,hits.length);
});
test('newly forged power is protected until a later reaction',()=>{const b=stable();b[24].power='surge';assert.deepEqual(expandHits(b,[24],new Set([24])).activated,[])});
test('all six power pairs swap without a match and activate once',()=>{
 for(const [a,b]of [['surge','surge'],['surge','burst'],['burst','burst'],['prism','surge'],['prism','burst'],['prism','prism']]){const g=new Game({mode:'free',seed:12});g.board=stable();g.board[24].power=a;g.board[25].power=b;assert.ok(comboInfo(g.board[24],g.board[25]));assert.ok(g.availableMoves().some(p=>p[0]===24&&p[1]===25));const r=g.play(24,25);assert.ok(r.valid);assert.equal(g.combos,1);assert.equal(g.used,1);assert.ok(r.frames.find(f=>f.kind==='clear').hits.length>=9);assert.ok(Game.restore(g.snapshot()))}
});
test('double prism clears every tile including all static',()=>{const g=new Game({mode:'free',seed:7});g.board=stable();g.board[24].power=g.board[25].power='prism';g.board.forEach(t=>t.glitch=true);const r=g.play(24,25);assert.equal(r.frames.find(f=>f.kind==='clear').hits.length,49);assert.equal(g.board.filter(t=>t.glitch).length,0)});
test('static counts follow actual board when struck or cleared next to',()=>{const g=new Game({runIndex:4,seed:42});g.board=stable();g.board[24].power='surge';g.board[25].power='burst';for(const i of [0,1,2,3,4,5,6])g.board[i].glitch=true;g.play(24,25);assert.equal(g.objectives().find(o=>o.label==='Purge static').value,7-g.board.filter(t=>t.glitch).length)});
test('reshuffle preserves every tile, power, and static with no starting match',()=>{for(let seed=1;seed<=25;seed++){const g=new Game({seed});g.board[3].power='prism';g.board[27].power='burst';g.board[27].glitch=true;const before=multiset(g.board);g.reshuffle();assert.deepEqual(multiset(g.board),before);assert.equal(matches(g.board).hits.length,0);assert.ok(g.availableMoves().length)}});
test('conveyor runs on the advertised move and carries tile contents',()=>{const g=new Game({runIndex:25,seed:88});assert.equal(g.beltIn,3);for(let n=1;n<=3;n++){const r=g.play(...g.availableMoves()[0]);assert.equal(r.frames.some(f=>f.kind==='belt'),n===3);if(n===3){const i=r.frames.findIndex(f=>f.kind==='belt'),before=r.frames[i-1].board.slice(21,28),after=r.frames[i].board.slice(21,28);before.unshift(before.pop());assert.deepEqual(after,before)}}assert.equal(g.beltIn,3)});
test('saving restores exact next refill sequence and outcomes',()=>{const g=new Game({runIndex:27,seed:987});g.play(...g.availableMoves()[0]);const restored=Game.restore(g.snapshot());for(let i=0;i<12&&!g.over;i++){const move=g.availableMoves()[0];g.play(...move);restored.play(...move);assert.deepEqual(restored.snapshot(),g.snapshot())}});
test('same daily date and move sequence is identical across clients',()=>{for(const day of ['2026-09-22','2026-09-23','2027-01-01']){const a=new Game({mode:'daily',day,seed:1}),b=new Game({mode:'daily',day,seed:999});for(let n=0;n<10&&!a.over;n++){assert.deepEqual(a.snapshot(),b.snapshot());const p=a.availableMoves()[0];a.play(...p);b.play(...p)}assert.deepEqual(a.snapshot(),b.snapshot())}});
test('daily reset uses UTC; consecutive dates produce different grids',()=>{assert.equal(dayKey(new Date('2026-09-22T23:59:59Z')),'2026-09-22');assert.equal(dayKey(new Date('2026-09-23T00:00:00Z')),'2026-09-23');assert.notDeepEqual(new Game({mode:'daily',day:'2026-09-22'}).board,new Game({mode:'daily',day:'2026-09-23'}).board)});
test('old saves migrate and completed original campaign unlocks Foundry',()=>{const storage={getItem:k=>k===LEGACY_KEY?JSON.stringify({unlocked:24,selected:24,complete:[0,24],best:12345}):null};const {profile:p}=loadProfile(storage);assert.equal(p.unlocked,25);assert.equal(p.best,12345);assert.deepEqual(p.complete,[0,24]);assert.equal(p.selected,24)});
test('malformed saved games are rejected safely',()=>{for(const s of [null,{}, {schema:1}, {...new Game().snapshot(),board:[]},{...new Game().snapshot(),counts:null},{...new Game().snapshot(),moves:-1}])assert.equal(Game.restore(s),null);const p=loadProfile({getItem:()=>'{broken'});assert.ok(p.warning);assert.equal(p.profile.unlocked,0)});
test('stored sessions are independent and cannot bypass campaign unlocks',()=>{const campaign=new Game({seed:1}),daily=new Game({mode:'daily',day:'2026-09-22'}),free=new Game({mode:'free',seed:3});const data={sessions:{campaign:campaign.snapshot(),daily:daily.snapshot(),free:free.snapshot()}};const {profile:p}=loadProfile({getItem:k=>k===SAVE_KEY?JSON.stringify(data):null});assert.equal(Object.keys(p.sessions).length,3);data.sessions.campaign=new Game({runIndex:29}).snapshot();assert.equal(loadProfile({getItem:k=>k===SAVE_KEY?JSON.stringify(data):null}).profile.sessions.campaign,undefined)});
test('daily records cannot unlock campaign; replay keeps best',()=>{const p=loadProfile({getItem:()=>null}).profile,g=new Game({mode:'daily',day:'2026-09-22'});g.won=true;g.over=true;g.used=20;g.moves=10;g.score=12345;recordResult(p,g);assert.equal(p.unlocked,0);assert.equal(p.daily[g.day].medal,3);g.score=100;g.used=25;recordResult(p,g);assert.equal(p.daily[g.day].best,12345);assert.equal(p.daily[g.day].fewest,20)});
test('free play remains playable with unlimited moves',()=>{const g=new Game({mode:'free',seed:91});for(let i=0;i<250;i++)g.play(...g.availableMoves()[0]);assert.equal(g.moves,null);assert.equal(g.over,false);assert.equal(g.used,250)});
test('generated boards and 900 campaign turns have no stalled or phantom state',()=>{for(let runIndex=0;runIndex<30;runIndex++)for(let seed=1;seed<=3;seed++){const g=new Game({runIndex,seed});for(let n=0;n<10&&!g.over;n++){assert.equal(matches(g.board).hits.length,0);assert.ok(g.availableMoves().length);g.play(...g.availableMoves()[0]);assert.ok(Game.restore(g.snapshot()))}}});
