/* FIRST KIN browser controller. No network, dependencies, or background time. */
const UI=(()=>{
 const $=id=>document.getElementById(id),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const SAVE='first-kin-campaign-v6';
 let s=Kin.create(),selected='oldM',panelName='people',sceneName='camp',buildType=null,regionSelection='home',field=null,encounter=null,busy=false,ready=false,hover=null;
 const camera={zoom:1,dx:0,dy:0};let pointer=null;let W=900,H=620,dpr=1,last=0,acc=0,time=0,toastTimer,stepTimer,fieldStamp='',positions={},walkStart=0,walkTargets={};
 const canvas=$('worldCanvas'),ctx=canvas.getContext('2d');
 Kin.firstPlans(s);
 const labels={rest:'Rest & recover',fire:'Tend the hearth',water:'Carry water',forage:'Gather greens',roots:'Dig roots',wood:'Gather wood',stone:'Gather stone',fiber:'Gather fiber',fish:'Fish the river',hunt:'Solo hunt',party:'Join group hunt',build:'Build placed sites',study:'Study the active discovery',plant:'Plant a growing plot',tend:'Water growing plots',harvest:'Harvest ripe plots',preserve:'Preserve four meat',scout:'Scout the frontier',story:'Share a memory'};
 const actionName=a=>a?.startsWith('watch:')?'Watch '+(Kin.get(s,a.split(':')[1])?.name||'someone'):a?.startsWith('teach:')?'Teach '+Kin.skillNames[a.split(':')[1]]:a?.startsWith('practice:')?'Practice '+Kin.skillNames[a.split(':')[1]]:a?.startsWith('craft:')?'Make '+Kin.recipes[a.split(':')[1]]?.name:labels[a]||'Rest & recover';
 const price=c=>Object.entries(c).map(([k,n])=>`${n} ${k}`).join(' · '),locked=()=>s.phase!=='plan'||busy;
 function toast(t){$('toast').textContent=t;$('toast').classList.remove('hidden');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.add('hidden'),4800)}
 function setHidden(id,hide){$(id).classList.toggle('hidden',hide)}
 function portraitCanvases(){if(!ready)return;document.querySelectorAll('canvas[data-art]').forEach(c=>{const z=Number(c.dataset.size)||80;c.width=z*2;c.height=z*2;View.portrait(c.getContext('2d'),Number(c.dataset.art),z*2)})}
 function face(p,size=44,cls=''){return `<canvas class="${cls}" data-art="${p.art}" data-size="${size}" aria-label="${esc(p.name)} portrait"></canvas>`}
 function autoSave(){if(s.started&&['plan','dinner'].includes(s.phase)){try{localStorage.setItem(SAVE,JSON.stringify(s))}catch{}}}
 function menu(){const el=$('saveMenu');el.classList.toggle('hidden');$('menuBtn').setAttribute('aria-expanded',String(!el.classList.contains('hidden')))}
 function closeMenu(){setHidden('saveMenu',true);$('menuBtn').setAttribute('aria-expanded','false')}
 function save(notify=false){if(!s.started){toast('Light the first hearth to begin.');return}if(!['plan','dinner'].includes(s.phase)){toast('Finish this sun before saving. Your last completed sun is safe.');return}try{localStorage.setItem(SAVE,JSON.stringify(s));if(notify)toast('Your people are saved on this device.')}catch{toast('This browser cannot store the save. Use Export save to keep it.')}}
 function restore(next){if(!Kin.valid(next)||next.phase==='run'||next.pending.length){toast('That file is not a complete FIRST KIN save. Your current family is unchanged.');return false}clearTimeout(stepTimer);s=next;s.started=true;selected=Kin.live(s)[0]?.id||s.people[0].id;field=null;encounter=null;busy=false;buildType=null;sceneName='camp';positions={};setHidden('intro',true);$('dinnerDialog').close();closeMenu();render();autoSave();return true}
 function load(){if(busy){toast('Return from the field and finish this sun first.');return}try{const saved=localStorage.getItem(SAVE);if(!saved){toast('No saved family yet.');return}if(restore(JSON.parse(saved)))toast('Your people are home.')}catch{toast('The save could not be read. You can import an exported save.')}}
 function download(name,data,type){const url=URL.createObjectURL(new Blob([data],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 function exportSave(){if(!s.started||!['plan','dinner'].includes(s.phase)){toast('Finish this sun before exporting.');return}download(`first-kin-sun-${s.sun}.json`,JSON.stringify(s,null,2),'application/json');toast('Save exported.')}
 async function importSave(file){if(!file)return;if(busy){toast('Finish this sun before importing.');return}if(file.size>5000000){toast('Choose a FIRST KIN save under 5 MB.');return}try{if(restore(JSON.parse(await file.text())))toast('Imported family restored.')}catch{toast('That file could not be read. Your current family is unchanged.')}}
 function newGame(){if(busy){toast('Finish this sun first.');return}if(s.started&&!window.confirm('Begin a new family? Export your current save first if you want to keep it.'))return;s=Kin.create();Kin.firstPlans(s);selected='oldM';positions={};field=null;buildType=null;sceneName='camp';$('dinnerDialog').close();closeMenu();setHidden('intro',false);render()}
 function begin(){s.started=true;setHidden('intro',true);autoSave();render();toast('Opening plans are ready. Place a family shelter beside a path, then commit the sun.')}
 function scene(name){if(field){toast('Return to the settlement to change views.');return}sceneName=name;buildType=null;render()}
 function panel(name){panelName=name;renderSide();document.querySelectorAll('[data-panel]').forEach(b=>b.classList.toggle('active',b.dataset.panel===name))}
 function select(id){if(!Kin.get(s,id))return;selected=id;panel('people')}
 function fieldToggle(value){s.fieldTrips=!!value;autoSave();if(!value)toast('Providers will resolve their field work automatically.');render()}
 function plan(slot,action){if(locked())return;Kin.plan(s,selected,Number(slot),action);autoSave();renderSide()}
 function repeat(){if(locked())return;if(!s.lastPlan){toast('Finish a sun to reuse its plans.');return}Kin.live(s).forEach(p=>s.plans[p.id]=[...(s.lastPlan[p.id]||['rest','rest'])]);autoSave();renderSide();toast('Previous plans restored. Check materials and the active discovery.')}
 function restAll(){if(locked())return;Kin.live(s).forEach(p=>s.plans[p.id]=['rest','rest']);autoSave();renderSide()}
 function options(p,current){const group=(name,items)=>`<optgroup label="${name}">${items.map(([value,label])=>`<option value="${value}" ${value===current?'selected':''}>${esc(label)}</option>`).join('')}</optgroup>`;
  return group('Daily work',Object.entries(labels))+group('Watch someone',Kin.live(s).filter(a=>a.id!==p.id).map(a=>['watch:'+a.id,'Watch '+a.name]))+group('Teach a skill',p.know.filter(k=>(p.hand[k]||0)>0).map(k=>['teach:'+k,'Teach '+Kin.skillNames[k]]))+group('Practice what you know',p.know.map(k=>['practice:'+k,'Practice '+Kin.skillNames[k]]))+group('Make a tool',Object.entries(Kin.recipes).map(([k,r])=>['craft:'+k,r.name+' · '+price(r.cost)]));
 }
 function renderPeople(){const p=Kin.get(s,selected)||s.people[0],plans=s.plans[p.id]||['rest','rest'];return `<div class="side-heading"><h2>Your people</h2><span>${Kin.live(s).length} at home</span></div><div class="roster">${s.people.map(a=>`<button title="${esc(a.name+' · '+a.role)}" class="person-choice ${a.id===p.id?'selected':''} ${a.alive?'':'dead'}" onclick="UI.select('${a.id}')">${face(a)}<span>${esc(a.name)}</span></button>`).join('')}</div><div class="selected-person">${face(p,78,'portrait-large')}<div class="person-info"><h3>${esc(p.name)}</h3><p>${esc(p.role)}</p><div class="person-status">${p.alive?`${Math.round(p.health)} health · ${Math.round(p.fatigue)} fatigue`:'Remembered by the community'}</div></div></div>${p.alive?`<div class="action-group"><label for="morningPlan">Morning</label><select id="morningPlan" onchange="UI.plan(0,this.value)" ${locked()?'disabled':''}>${options(p,plans[0])}</select></div><div class="action-group"><label for="afternoonPlan">Afternoon</label><select id="afternoonPlan" onchange="UI.plan(1,this.value)" ${locked()?'disabled':''}>${options(p,plans[1])}</select></div>`:''}<details class="skill-details" open><summary>Understanding → practiced hands</summary>${Object.entries(Kin.skillNames).filter(([k])=>p.know.includes(k)||(p.hand[k]||0)>0).map(([k,n])=>`<div class="skill-line"><span>${n}<small>${p.know.includes(k)?'Understood':'Not understood'}</small></span><div class="pips" aria-label="${p.hand[k]||0} of 5 practiced">${Array.from({length:5},(_,i)=>`<i class="${i<(p.hand[k]||0)?'on':''}"></i>`).join('')}</div></div>`).join('')||'<p class="muted-copy">Start with Watch. Choose someone demonstrating a skill in the same part of the day.</p>'}</details><div class="plan-summary"><h3>The whole day</h3>${Kin.live(s).map(a=>`<button class="plan-row" onclick="UI.select('${a.id}')"><b>${esc(a.name)}</b><span>${esc(actionName(s.plans[a.id]?.[0]))}</span><span>${esc(actionName(s.plans[a.id]?.[1]))}</span></button>`).join('')}</div><div class="plan-tools"><button onclick="UI.repeat()" ${locked()?'disabled':''}>Reuse last sun</button><button onclick="UI.restAll()" ${locked()?'disabled':''}>Rest everyone</button></div><p class="muted-copy">Watching teaches understanding; practice builds ability. A provider away on a hunt cannot be watched from camp.</p>`}
 function chooseBuild(type){if(locked()){toast('Place buildings between suns.');return}buildType=type;sceneName='camp';render()}
 function zoom(amount){if(sceneName==='region'||field?.scene==='fish')return;if(!amount){camera.zoom=1;camera.dx=0;camera.dy=0}else camera.zoom=Math.max(.8,Math.min(2.2,camera.zoom+amount));$('zoomLevel').textContent=Math.round(camera.zoom*100)+'%'}
 function cancelBuild(){buildType=null;render()}
 function renderBuild(){return `<div class="side-heading"><h2>Make a home</h2><span>${Kin.capacity(s)} places</span></div><p class="muted-copy">Place a site on open ground, then assign Build. A finished building works when a path connects it to the hearth.</p><div class="build-list">${Object.entries(Kin.buildings).map(([k,b])=>{const unavailable=b.tech&&!s.research.done.includes(b.tech);return `<button class="build-card ${buildType===k?'selected':''} ${unavailable?'locked':''}" onclick="UI.chooseBuild('${k}')" ${unavailable||locked()?'disabled':''}><strong>${b.name}</strong><small>${b.desc}</small><span class="price">${unavailable?'Discover '+Kin.techs[b.tech].name:price(b.cost)+(b.work?' · '+b.work+' work':'')}</span></button>`}).join('')}</div><div class="building-status"><h3>At the hearth</h3>${s.buildings.filter(b=>Kin.buildings[b.type]).map(b=>`<span class="${!b.done||!Kin.connected(s,b)?'warn':''}">${Kin.buildings[b.type].name}: ${!b.done?'building '+b.work+'/'+Kin.buildings[b.type].work:Kin.connected(s,b)?'working':'needs a path'}</span>`).join('')||'<span>The cave shelters your first six people.</span>'}</div><p class="muted-copy">Supplies: ${['hide','bone','seed','preserved'].map(k=>s.stock[k]+' '+k).join(' · ')}<br>Tools: ${Object.entries(s.tools).filter(([,n])=>n>0).map(([k,n])=>n+' '+(Kin.recipes[k]?.name.toLowerCase()||'digging tool')).join(' · ')}</p>`}
 function research(id){if(locked())return;const tech=Kin.techs[id];if(!tech||tech.requires.some(k=>!s.research.done.includes(k))||s.research.done.includes(id))return;s.research.active=id;autoSave();renderSide();toast('Assign Study to explore '+tech.name+'.')}
 function renderDiscover(){return `<div class="side-heading"><h2>Shared knowledge</h2><span>${s.research.done.length}/5 discoveries</span></div><p class="muted-copy">Choose a discovery, then assign Study. Practiced hands in the related skill contribute twice as much. Knowledge belongs to the whole community.</p>${Object.entries(Kin.techs).map(([id,t])=>{const done=s.research.done.includes(id),active=s.research.active===id,blocked=t.requires.some(k=>!s.research.done.includes(k)),n=Math.min(t.need,s.research.progress[id]||0);return `<div class="discovery ${done?'done':active?'active':''}"><div class="discovery-header"><h3>${t.name}</h3><small>${done?'Known':n+'/'+t.need}</small></div><p>${t.desc}</p><div class="track"><i style="width:${n/t.need*100}%"></i></div><small>${Kin.skillNames[t.skill]} helps${t.requires.length?' · follows '+t.requires.map(k=>Kin.techs[k].name).join(', '):''}</small>${done?'':`<button onclick="UI.research('${id}')" ${locked()||blocked||active?'disabled':''}>${blocked?'Earlier discovery needed':active?'Current discovery':'Explore this'}</button>`}</div>`}).join('')}`}
 function reqList(title,items){return `<div class="requirements"><h3>${title}</h3>${items.map(r=>`<div class="requirement ${r.ok?'met':''}"><b aria-label="${r.ok?'Met':'Needed'}">${r.ok?'✓':'○'}</b><span>${r.text}</span></div>`).join('')}</div>`}
 function welcome(){if(!Kin.welcome(s)){toast('Prepare housing, food and trust. Council shows what is needed.');return}autoSave();render();toast('Another family has joined your people.')}
 function renderCouncil(){const r=Kin.requirements(s),pop=Kin.live(s).length;return `<div class="side-heading"><h2>${s.stage==='village'?'A lasting village':s.stage==='tribe'?'The growing tribe':'From one family'}</h2><span>${s.trust} trust</span></div><div class="council-card"><h3>Welcome new kin</h3><p>${s.settlerWave>=3?'All three neighboring families have joined. Care for the twelve people whose lives you now share.':`A family can arrive from sun ${3+s.settlerWave*3}. Prepare ${pop+2} places to sleep, ${pop+2} food and ${3+s.settlerWave*2} trust.`}</p><button class="primary" onclick="UI.welcome()" ${!Kin.canWelcome(s)||busy?'disabled':''}>${s.settlerWave>=3?'Community gathered':'Welcome a family'}</button></div>${reqList('Family → Tribe',r.tribe)}${reqList('Tribe → Village',r.village)}<p class="muted-copy">Growing means more mouths, more hands, and more people who can carry knowledge. Tribe and village are milestones you can keep building beyond.</p>`}
 function renderMemory(){return `<div class="side-heading"><h2>What we carry</h2><span>${s.chronicle.length} suns remembered</span></div><p class="muted-copy">Your community's history grows from what actually happens. Lessons pass between named people.</p>${s.chronicle.slice(-12).reverse().map(c=>`<div class="memory-entry"><small>Sun ${c.sun}</small><p>“${esc(c.line)}”</p></div>`).join('')||'<div class="memory-entry"><small>The beginning</small><p>Six people. One fire. A whole world still ahead.</p></div>'}<h3>Knowledge passed on</h3>${s.lessons.filter(l=>l.type==='understanding').slice(-12).reverse().map(l=>`<p class="muted-copy">Sun ${l.sun} · ${esc(Kin.get(s,l.learner)?.name)} learned ${Kin.skillNames[l.skill]}${l.teacher?' from '+esc(Kin.get(s,l.teacher)?.name):' through discovery'}.</p>`).join('')||'<p class="muted-copy">Give someone a lesson worth remembering.</p>'}<div class="council-card"><h3>A world with room for lore</h3><p>This first world and its communities are fictional. Specific Indigenous histories and stories can be developed as distinct, attributed world chapters with their creators.</p></div>`}
 function renderSide(){$('sideContent').innerHTML=({people:renderPeople,build:renderBuild,discover:renderDiscover,council:renderCouncil,memory:renderMemory}[panelName]||renderPeople)();portraitCanvases()}
 function render(){const pop=Kin.live(s).length,cap=Kin.capacity(s),food=Kin.reserve(s);$('sunLabel').textContent='Sun '+s.sun;$('seasonLabel').textContent=Kin.season(s)+' · Year '+(1+Math.floor((s.sun-1)/24));$('weatherLabel').textContent=Kin.weather(s)+' weather';const resources=[[pop+'/'+cap,'People','sheltered places',pop>cap],[food,'Food',pop?(food/pop).toFixed(1)+' suns in reserve':'at home',food<pop],[s.stock.water,'Water','for people & plots',s.stock.water<Math.ceil(pop/4)],[s.stock.wood,'Wood','building & fire',s.stock.wood<2],[s.stock.stone,'Stone','paths & tools',false],[s.stock.fiber,'Fiber','binding & baskets',false],[s.fire,'Hearth',s.fire?'embers kept':'fire is out',s.fire<2],[s.trust,'Trust','shared experience',false]];$('resourceBar').innerHTML=resources.map(([n,name,sub,low])=>`<div class="resource ${low?'low':''}"><span>${name}</span><b>${n}</b><small>${sub}</small></div>`).join('');
  $('settlementView').classList.toggle('active',sceneName==='camp');$('regionView').classList.toggle('active',sceneName==='region');$('settlementView').disabled=!!field;$('regionView').disabled=!!field;setHidden('mapZoom',sceneName==='region'||field?.scene==='fish');setHidden('buildBanner',!buildType);if(buildType)$('buildLabel').textContent=Kin.buildings[buildType].name+' · '+price(Kin.buildings[buildType].cost)+' · tap open ground';
  $('mapTitle').innerHTML=field?`<span>${field.scene==='party'?'THE GREAT HUNT':field.scene==='fish'?'AT THE RIVER':'THE PROVIDER'}</span><h2>${field.actors.map(p=>esc(p.name)).join(' & ')}</h2>`:sceneName==='region'?'<span>BEYOND THE HEARTH</span><h2>The known world</h2>':'<span>'+({family:'THE FIRST HEARTH',tribe:'MANY HANDS, ONE HEARTH',village:'A PLACE TO BELONG'}[s.stage])+'</span><h2>Hearth Valley</h2>';
  $('mapHint').textContent=field?(field.scene==='party'?'Place hunters on the near side of the clearing.':field.scene==='fish'?'Pull when the rod bends.':'Tap ground to move. Strike when close.'):buildType?'Finished buildings need a path to the hearth.':sceneName==='region'?'Select a discovered place. Assign Scout to reveal more.':'Select a person to plan their day.';
  $('stageProgress').innerHTML=['family','tribe','village'].map((x,i)=>`<span class="${i<=['family','tribe','village'].indexOf(s.stage)?'reached':''}"><i>${i+1}</i>${x[0].toUpperCase()+x.slice(1)}</span>`).join('<b>—</b>');$('fieldToggle').checked=s.fieldTrips;$('fieldToggle').disabled=busy;
  $('runButton').disabled=busy||!pop;$('runButton').textContent=busy?'Sun in progress…':s.phase==='dinner'?'Around the fire →':'Commit the sun →';
  const entries=s.today.events.slice(-3);$('eventFeed').innerHTML=entries.map(x=>`<p>${esc(x)}</p>`).join('')||'<p>The first plans are set: teach firecraft, gather food, and give the young kin a skill to practice.</p>';renderSide();renderRegion();renderField();
 }
 function renderRegion(){setHidden('regionCard',sceneName!=='region'||!!field);if(sceneName!=='region')return;const p=Kin.places.find(p=>p.id===regionSelection)||Kin.places[0],seen=s.region.seen.includes(p.id);$('regionCard').innerHTML=seen?`<h3>${p.name}</h3><p>${p.desc}</p><div class="region-actions">${p.type==='neighbor'?`<button onclick="UI.trade('${p.id}')" ${locked()||!s.research.done.includes('exchange')?'disabled':''}>${p.id==='amber'?'Trade 4 preserved food for 8 fiber':'Trade 5 fiber for 8 stone'}</button>`:''}${['forest','river','stone'].includes(p.type)?`<button onclick="UI.outpost('${p.id}')" ${locked()||!s.research.done.includes('exchange')||s.region.outposts.includes(p.id)?'disabled':''}>${s.region.outposts.includes(p.id)?'Outpost working · +2 each dawn':'Establish outpost · 8 wood, 4 stone, 4 preserved'}</button>`:''}${p.id==='home'?'<button onclick="UI.scene(\'camp\')">Return to the settlement</button>':''}</div>`:'<h3>Beyond the known paths</h3><p>Assign Scout to someone in the People panel. Each scouting action reveals the next reachable place.</p>'}
 function trade(id){const err=Kin.trade(s,id);toast(err||'The exchange is complete.');autoSave();render()}
 function outpost(id){const err=Kin.outpost(s,id);toast(err||'An outpost now supplies Hearth Valley each dawn.');autoSave();render()}
 function run(){if(!s.started){begin();return}if(busy)return;if(s.phase==='dinner'){showDinner();return}if(!Kin.start(s))return;busy=true;buildType=null;sceneName='camp';render();stepTimer=setTimeout(advance,200)}
 function targetsForSlot(){walkTargets={};walkStart=time;Kin.live(s).forEach((p,i)=>{const a=s.plans[p.id]?.[s.slot]||'rest',t={wood:[8,3],stone:[2,3],fiber:[10,8],forage:[8,8],roots:[3,9],water:[11,6],fish:[11,6],hunt:[9,3],party:[9,3],scout:[10,1],fire:[5,6],build:[s.buildings.find(b=>!b.done)?.x??6,s.buildings.find(b=>!b.done)?.y??6]}[a];const base=t||[4.3+(i%4)*.8,6.6+Math.floor(i/4)*.65];const old=positions[p.id]||p;walkTargets[p.id]={from:{x:old.x,y:old.y},to:{x:base[0]+(t?(i%2)*.35:0),y:base[1]}}})}
 function advance(){if(!busy||field)return;if(s.pending.length){encounter=s.pending[0];if(s.fieldTrips){field=Field.create(s,encounter);camera.zoom=1;camera.dx=0;camera.dy=0;$('zoomLevel').textContent='100%';fieldStamp='';acc=0;render();return}const result=Kin.autoResult(s,encounter);Kin.applyField(s,encounter,result);encounter=null;render();stepTimer=setTimeout(advance,250);return}
  if(s.slot<2){targetsForSlot();Kin.resolveSlot(s);render();stepTimer=setTimeout(advance,1000);return}Kin.dinner(s);busy=false;positions={};render();autoSave();showDinner();
 }
 function showDinner(){const d=s.today,pop=Kin.live(s).length;$('dinnerTitle').textContent='The end of sun '+s.sun;$('dinnerBody').innerHTML=`<div class="dinner-metrics"><div><b>${d.fed??0}</b><small>people fed</small></div><div><b>${Kin.reserve(s)}</b><small>food for tomorrow</small></div><div><b>${d.learned.length}</b><small>steps in learning</small></div></div><div class="dinner-voice"><p>“${esc(s.chronicle.at(-1)?.line||'The hearth is quiet.')}”</p></div><div class="dinner-events">${d.short?`<p>${d.short} food missing from the shared meal.</p>`:''}${d.dry?'<p>Water ran short. Someone needs to carry water.</p>':''}${d.exposed?'<p>The cold reached the camp. Restore the fire and connect shelters.</p>':''}${d.spoiled?`<p>${d.spoiled} fresh food spoiled. A storehouse and smoke rack help keep a surplus.</p>`:''}${d.learned.slice(0,6).map(t=>`<p>${esc(t)}</p>`).join('')}${!pop?'<p>No one remains at the hearth. Begin a new family from the menu.</p>':''}</div>`;if(!$('dinnerDialog').open)$('dinnerDialog').showModal()}
 function sleep(){if(!Kin.sleep(s))return;$('dinnerDialog').close();field=null;positions={};render();autoSave();if(s.sun===3)toast('Another family can join from today. Check Council for housing, food and trust.')}
 function renderField(){setHidden('fieldControls',!field);if(!field)return;const f=field;$('fieldControls').innerHTML=`<div class="field-title"><h3>${f.scene==='party'?'The great hunt':f.scene==='fish'?'Fish for the journey and home':'A provider in the field'}</h3><span>${f.done?'Return to camp':f.phase==='plan'?'Preparation':f.paused?'Paused':Math.floor(f.time)+' seconds'}</span></div><p class="field-message" aria-live="polite">${esc(f.message)}</p>${f.scene==='party'&&f.phase==='plan'?`<div class="party-list">${f.actors.map((a,i)=>`<div class="party-member ${i===f.selected?'selected':''}"><button onclick="UI.fieldSelect(${i})">${esc(a.name)}</button><select aria-label="Role for ${esc(a.name)}" onchange="UI.role(${i},this.value)">${Object.entries(Field.roles).map(([k,r])=>`<option value="${k}" ${a.role===k?'selected':''}>${r.name}</option>`).join('')}</select></div>`).join('')}</div><p class="muted-copy">${Field.roles[f.actors[f.selected].role].desc} Tap the map to position this person. Longarms need a bow each.</p>`:''}<div class="field-buttons">${f.done?'<button class="primary" onclick="UI.returnHome()">Bring the result home →</button>':f.phase==='plan'?'<button class="primary" onclick="UI.commitHunt()">Commit the hunt →</button><button onclick="UI.returnEarly()">Return without hunting</button>':`<button class="primary" onclick="UI.fieldAction()" ${f.paused?'disabled':''}>${f.scene==='fish'?(f.phase==='biting'?'Pull now!':'Pull the line'):f.scene==='hunt'?'Strike':'Speed: ×'+(f.speed||1)}</button><button onclick="UI.pauseField()">${f.paused?'Resume':'Pause'}</button><button onclick="UI.returnEarly()">Return early</button>`}</div>`;fieldStamp=[f.phase,f.paused,f.message,Math.floor(f.time),f.selected].join('|')}
 function fieldSelect(i){if(field?.phase==='plan'){field.selected=i;renderField()}}
 function role(i,r){if(!field)return;if(!Field.setRole(field,i,r))toast('A Longarm needs an available bow.');renderField()}
 function commitHunt(){if(field){Field.commit(field);renderField()}}
 function fieldAction(){if(!field||field.paused||field.done)return;if(field.scene==='fish')Field.hook(field);if(field.scene==='hunt')Field.attack(field);if(field.scene==='party')field.speed=field.speed===3?1:3;renderField()}
 function pauseField(){if(!field||field.done)return;field.paused=!field.paused;renderField()}
 function returnEarly(){if(!field)return;Field.finish(field,field.scene==='fish'&&field.caught>0);renderField()}
 function returnHome(){if(!field?.done||!encounter)return;if(!Kin.applyField(s,encounter,Field.result(field))){toast('This field result could not be applied.');return}field=null;encounter=null;render();stepTimer=setTimeout(advance,350)}
 function clickMap(ev){if(!s.started)return;const rect=canvas.getBoundingClientRect(),x=ev.clientX-rect.left,y=ev.clientY-rect.top;if(sceneName==='region'){regionSelection=View.regionHit(x,y,W,H)||regionSelection;renderRegion();return}const at=View.unproject(x,y,View.metrics(W,H,camera));if(field){Field.tap(field,at.x,at.y);renderField();return}if(buildType){const err=Kin.place(s,buildType,at.x,at.y);if(err)toast(err);else{if(buildType!=='trail')buildType=null;autoSave();render()}return}
  let nearest=null,dist=50;Kin.live(s).forEach(p=>{const pp=View.project((positions[p.id]||p).x,(positions[p.id]||p).y,View.metrics(W,H,camera)),d=Math.hypot(x-pp.x,y-(pp.y-25));if(d<dist){dist=d;nearest=p}});if(nearest)select(nearest.id);
 }
 function resize(){const r=$('canvasShell').getBoundingClientRect();W=r.width;H=r.height;dpr=Math.min(2,window.devicePixelRatio||1);canvas.width=Math.round(W*dpr);canvas.height=Math.round(H*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);drawIntro()}
 function drawIntro(){if(!ready)return;const c=$('introPeople'),r=c.getBoundingClientRect(),w=r.width||420,h=r.height||420;c.width=Math.round(w*2);c.height=Math.round(h*2);const cctx=c.getContext('2d');cctx.scale(2,2);const ps=[0,1,2,3,4,5];ps.forEach((j,i)=>{const x=w*(.15+(i%3)*.32),y=h*(i<3?.57:.95),size=Math.min(w*.58,h*.63);View.human(cctx,s.people[j],x,y,size,0,false,false)})}
 function frame(now){const dt=last?Math.min(.1,(now-last)/1000):0;last=now;time+=dt;if(field&&!document.hidden){acc+=dt*(field.scene==='party'?(field.speed||1):1);while(acc>=1/30){Field.step(field,1/30);acc-=1/30}const stamp=[field.phase,field.paused,field.message,Math.floor(field.time),field.selected].join('|');if(stamp!==fieldStamp)renderField()}
  if(busy&&!field){const t=Math.min(1,(time-walkStart)/1.1);Object.entries(walkTargets).forEach(([id,p])=>positions[id]={x:p.from.x+(p.to.x-p.from.x)*t,y:p.from.y+(p.to.y-p.from.y)*t,moving:t<1})}
  if(ready)View.draw(ctx,W,H,s,{scene:sceneName,selected,time,build:buildType,hover,actorPositions:positions,regionSelection,camera},field);requestAnimationFrame(frame)
 }
 canvas.addEventListener('pointerdown',e=>{pointer={x:e.clientX,y:e.clientY,lastX:e.clientX,lastY:e.clientY,drag:false};canvas.setPointerCapture(e.pointerId)});
 canvas.addEventListener('pointermove',e=>{const r=canvas.getBoundingClientRect();hover=View.unproject(e.clientX-r.left,e.clientY-r.top,View.metrics(W,H,camera));if(pointer&&sceneName==='camp'&&field?.scene!=='fish'){if(Math.hypot(e.clientX-pointer.x,e.clientY-pointer.y)>6)pointer.drag=true;if(pointer.drag){camera.dx=Math.max(-W,Math.min(W,camera.dx+e.clientX-pointer.lastX));camera.dy=Math.max(-H,Math.min(H,camera.dy+e.clientY-pointer.lastY))}pointer.lastX=e.clientX;pointer.lastY=e.clientY}});
 canvas.addEventListener('pointerup',e=>{if(pointer&&!pointer.drag)clickMap(e);pointer=null});canvas.addEventListener('pointercancel',()=>pointer=null);canvas.addEventListener('pointerleave',()=>hover=null);

 document.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA','BUTTON'].includes(e.target.tagName)||$('helpDialog').open||$('dinnerDialog').open)return;if(e.key==='Escape'){cancelBuild();return}if(!field)return;if(e.code==='Space'){e.preventDefault();fieldAction();return}if(field.scene==='hunt'&&!field.paused){const d={ArrowUp:[0,-1],w:[0,-1],ArrowDown:[0,1],s:[0,1],ArrowLeft:[-1,0],a:[-1,0],ArrowRight:[1,0],d:[1,0]}[e.key];if(d){e.preventDefault();const p=field.actors[0];Field.tap(field,Math.round(p.x)+d[0],Math.round(p.y)+d[1])}}});
 document.addEventListener('visibilitychange',()=>{if(document.hidden&&field&&!field.done){field.paused=true;renderField()}});
 new ResizeObserver(resize).observe($('canvasShell'));window.addEventListener('beforeunload',autoSave);
 try{setHidden('continueBtn',!localStorage.getItem(SAVE))}catch{setHidden('continueBtn',true)}
 Promise.all(ART.map(src=>new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=reject;im.src=src}))).then(images=>{View.assets(images);ready=true;resize();render();requestAnimationFrame(frame)}).catch(()=>{toast('The character artwork could not load. Reopen the complete game file.');render()});
 render();
 return{menu,save,load,exportSave,importSave,newGame,begin,scene,panel,select,fieldToggle,plan,repeat,restAll,chooseBuild,cancelBuild,zoom,research,welcome,trade,outpost,run,sleep,fieldSelect,role,commitHunt,fieldAction,pauseField,returnEarly,returnHome,help:()=>$('helpDialog').showModal()};
})();
