"use strict";
window.NSUI=(()=>{
  const panel=$('panel'),modal=$('modal');
  const achievements={first:['First cut','Defeat an enemy.'],relay:['Signal breaker','Extract from a district.'],ghost:['Untouchable','Clear a district without taking a hit.'],collector:['Data ghost','Find all three data shards in one district.'],city:['City of light','Complete all six districts.'],ronin:['True Ronin','Complete the campaign on Ronin.']};
  const time=value=>`${String(Math.floor(value/60)).padStart(2,'0')}:${String(Math.floor(value%60)).padStart(2,'0')}`;
  let toastTimer=0,refreshAt=0,lastHint='',pauseReason='';
  function announce(message){$('announcer').textContent=message;}
  function toast(message){clearTimeout(toastTimer);$('toast').textContent=message;$('toast').classList.add('visible');toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),3200);}
  function showPanel(html,title=false){overlay.hidden=false;overlay.classList.toggle('centered',!title);panel.className=title?'panel title-panel':'panel';panel.innerHTML=html;panel.focus({preventScroll:true});$('pauseBtn').disabled=mode==='title'||mode==='clear'||mode==='gameover'||mode==='victory';refreshAt=0;}
  function hidePanel(){overlay.hidden=true;$('pauseBtn').disabled=false;stage.focus({preventScroll:true});refreshAt=0;}
  function title(){
    mode='title';running=false;clearInput();bossVisibility(false);P.dead=false;P.inv=0;P.x=W*.78;P.y=GY-P.h;P.face=-1;P.vx=0;P.grounded=true;$('tutorialHint').hidden=true;lastHint='';
    const saved=NSStore.data.checkpoint;
    showPanel(`<p class="kicker">SKAB ORIGINAL // MIDNIGHT PROTOCOL</p><h1 class="title">NEON<span>SHINOBI</span></h1><p class="lead">One blade against a city under control.<br>Break the relays. Derez the guardians. Bring back the light.</p><div class="feature-line"><span><b>06</b> DISTRICTS</span><span><b>03</b> GUARDIANS</span><span><b>01</b> SHOT AT FREEDOM</span></div><label class="difficulty-picker">DIFFICULTY <select id="difficulty"><option value="story">Story</option><option value="arcade" selected>Arcade</option><option value="ronin">Ronin</option></select></label><div id="difficultyDescription"></div><div class="actions">${saved?`<button class="primary" id="continueRun">Continue · District ${saved.district+1}</button>`:''}<button class="${saved?'secondary':'primary'}" id="newRun">${saved?'New campaign':'Enter the city →'}</button><button class="secondary" id="titleHelp">How to play</button></div><p class="panel-note">Keyboard · Touch · Gamepad<br>Progress saves at the start of each district.</p>`,true);
    const descriptions={story:'7 hearts · slower enemies · gentler guardians',arcade:'5 hearts · original combat intensity · standard score',ronin:'4 hearts · faster enemies · tougher guardians · 1.4× score'};
    const describe=()=>{$('difficultyDescription').textContent=descriptions[$('difficulty').value];};describe();$('difficulty').addEventListener('change',describe);
    $('newRun').addEventListener('click',()=>{const level=$('difficulty').value;if(NSStore.data.checkpoint)confirmNew(level);else NSCampaign.newRun(level);});
    $('continueRun')?.addEventListener('click',()=>NSCampaign.resume());$('titleHelp').addEventListener('click',openHelp);
    $('objective').textContent='AWAITING SIGNAL';$('wavelbl').textContent='06 DISTRICTS · 01 CITY';$('wavebanner').style.opacity=0;
  }
  function confirmNew(level){showPanel(`<p class="kicker">NEW SIGNAL</p><h2>Start a new campaign?</h2><p class="lead">This replaces your current district checkpoint. Your records and achievements stay with you.</p><div class="actions"><button class="primary" id="confirmNew">Start new campaign</button><button id="cancelNew">Keep checkpoint</button></div>`);$('confirmNew').onclick=()=>NSCampaign.newRun(level);$('cancelNew').onclick=title;}
  function pause(reason=''){
    if(mode!=='playing')return;mode='paused';running=false;clearInput();accumulator=0;pauseReason=reason;pausedPanel();
  }
  function pausedPanel(){const state=NSCampaign.state;showPanel(`<p class="kicker">SIGNAL HELD // DISTRICT ${state.district+1}</p><h2>Take a breath.</h2><p class="lead">${pauseReason?pauseReason+'. ':''}Your run is paused. The city can wait.</p><div class="actions"><button class="primary" id="resumeRun">Resume run</button><button id="pauseHelp">Controls</button><button id="pauseSettings">Settings</button><button id="retryRun">Retry district</button><button id="returnTitle">Title screen</button></div><p class="panel-note">Retry restarts this district from its saved entry point.<br>Leaving the page keeps that checkpoint.</p>`);$('resumeRun').onclick=unpause;$('pauseHelp').onclick=openHelp;$('pauseSettings').onclick=openSettings;$('retryRun').onclick=confirmRetry;$('returnTitle').onclick=title;}
  function unpause(){if(mode!=='paused'||modal.open)return;clearInput();mode='playing';running=true;accumulator=0;tPrev=performance.now();initAudio();hidePanel();}
  function togglePause(){if(modal.open){modal.close();return;}if(mode==='playing')pause();else if(mode==='paused')unpause();else if(mode==='title')$('continueRun')?NSCampaign.resume():$('newRun')?.click();}
  function confirmRetry(){showPanel(`<p class="kicker">RETRY DISTRICT</p><h2>Return to the checkpoint?</h2><p class="lead">Score and pickups earned in this district will reset. Your earlier districts and upgrades are saved.</p><div class="actions"><button class="primary" id="confirmRetry">Retry checkpoint</button><button id="cancelRetry">Keep playing</button></div>`);$('confirmRetry').onclick=()=>NSCampaign.resume();$('cancelRetry').onclick=()=>{pauseReason='';pausedPanel();};}
  function openModal(titleText,html){pause();clearInput();$('modalTitle').textContent=titleText;$('modalBody').innerHTML=html;if(!modal.open)modal.showModal();}
  function openHelp(){openModal('Know your edge',`<p class="modal-copy">Disable all three relays in each district, defeat its guardian if present, then reach the extraction gate on the right. You can always turn back. Yellow diamonds are optional data shards; green stations repair two hearts.</p><table><thead><tr><th>Action</th><th>Keyboard</th><th>Pad / touch</th></tr></thead><tbody><tr><td>Move</td><td><kbd>A D / ← →</kbd></td><td>D-pad / left stick</td></tr><tr><td>Double jump</td><td><kbd>Space / W / ↑</kbd></td><td>A / D-pad up</td></tr><tr><td>Slash · hold to chain</td><td><kbd>J / K</kbd></td><td>B</td></tr><tr><td>Launcher</td><td>Hold jump + slash</td><td>Hold A + B</td></tr><tr><td>Dash / air slam</td><td><kbd>Shift / L / S / ↓</kbd></td><td>X / D-pad down</td></tr><tr><td>Rage · at 100%</td><td><kbd>R</kbd></td><td>Y</td></tr><tr><td>Pause</td><td><kbd>Esc / P</kbd></td><td>Start</td></tr><tr><td>Mute</td><td><kbd>M</kbd></td><td>Settings</td></tr></tbody></table><p class="modal-copy">Dash through attacks. Jump over ground shockwaves. Move away from marked falling blades. A yellow <b>!</b> warns of an incoming strike. Hit smaller enemies to interrupt them; guardians keep their attack pattern.</p><p class="modal-copy">Chain kills quickly for score multipliers. Rage clears nearby threats and damages guardians. Choose an upgrade after each district; checkpoints preserve earlier progress. Gamepad menus: D-pad to select, A to confirm, B to close a dialog.</p>`);}
  function applySettings(){document.body.classList.toggle('reduced-motion',NSStore.settings.reducedMotion);if(OUTPUT&&AC)OUTPUT.gain.setTargetAtTime(NSStore.settings.sound?NSStore.settings.volume*.65:0,AC.currentTime,.03);$('saveStatus').textContent=NSStore.available?'LOCAL CHECKPOINTS':'SAVES UNAVAILABLE · SESSION ONLY';$('saveStatus').classList.toggle('save-warning',!NSStore.available);}
  function openSettings(){openModal('Tune your signal',`<label class="setting">Sound effects <input id="soundSetting" type="checkbox" ${NSStore.settings.sound?'checked':''}></label><label class="setting">Volume <input id="volumeSetting" type="range" min="0" max="100" value="${Math.round(NSStore.settings.volume*100)}"></label><label class="setting">Reduce motion & flashes <input id="motionSetting" type="checkbox" ${NSStore.settings.reducedMotion?'checked':''}></label><label class="setting">Touch vibration <input id="hapticSetting" type="checkbox" ${NSStore.settings.haptics?'checked':''}></label><p class="modal-copy">Reduced motion disables screen shake and full-screen flashes, and lowers particle density. Settings and district checkpoints are saved in this browser.</p><div class="actions"><button id="settingsRecords">View records & achievements</button></div><p class="modal-copy">${NSStore.available?'Local saves are available.':'Browser storage is unavailable. You can play and retry during this session, but progress may not survive closing the page.'}</p>`);
    $('settingsRecords').onclick=records;
    for(const [id,key] of [['soundSetting','sound'],['motionSetting','reducedMotion'],['hapticSetting','haptics']])$(id).addEventListener('change',event=>{NSStore.setSetting(key,event.target.checked);initAudio();applySettings();});
    $('volumeSetting').addEventListener('input',event=>{NSStore.setSetting('volume',Number(event.target.value)/100);initAudio();applySettings();});}
  function toggleSound(){NSStore.setSetting('sound',!NSStore.settings.sound);applySettings();toast(NSStore.settings.sound?'Sound on':'Sound muted');}
  function records(){const runs=NSStore.data.runs;openModal('Shinobi records',`<p class="modal-copy">Personal best: <b>${NSStore.data.best.toLocaleString()}</b> · Local records on this device</p>${runs.length?`<table><thead><tr><th>Score</th><th>Mode</th><th>Progress</th><th>Time</th></tr></thead><tbody>${runs.map(r=>`<tr><td>${r.score.toLocaleString()}</td><td>${r.difficulty.toUpperCase()}${r.cycle?' +'+r.cycle:''}</td><td>${r.won?'CLEAR':'District '+r.district}</td><td>${time(r.time)}</td></tr>`).join('')}</tbody></table>`:'<p class="empty-records">Your story starts with the first run.</p>'}<div class="achievements">${Object.entries(achievements).map(([id,entry])=>`<div class="achievement ${NSStore.data.achievements.includes(id)?'unlocked':''}"><strong>${NSStore.data.achievements.includes(id)?'◆':'◇'} ${entry[0]}</strong>${entry[1]}</div>`).join('')}</div>`);}
  function stats(items){return `<div class="stats-grid">${items.map(([value,label])=>`<div><strong>${value}</strong><span>${label}</span></div>`).join('')}</div>`;}
  function districtClear(result){showPanel(`<p class="kicker">DISTRICT ${NSCampaign.state.district+1} // SIGNAL RESTORED</p><h2>${NSCampaign.current.name} is free.</h2>${stats([['+'+result.bonus,'CLEAR BONUS'],[result.shards+'/3','DATA SHARDS'],[result.hits,'HITS TAKEN'],[time(result.time),'DISTRICT TIME']])}<p class="lead">Choose your next upgrade. You recover two hearts before the next district.</p><div class="upgrades">${Object.entries(NSCampaign.upgradeInfo).map(([key,item])=>{const level=NSCampaign.state.upgrades[key];return `<button class="upgrade" data-upgrade="${key}" ${level>=3?'disabled':''}><span class="glyph" aria-hidden="true">${item.icon}</span><strong>${item.name}</strong><small>${item.detail}</small><span class="level">${level>=3?'MAXED':'LEVEL '+level+' → '+(level+1)}</span></button>`;}).join('')}</div><div class="actions"><button id="repairChoice">Full repair instead</button></div>`);for(const b of panel.querySelectorAll('[data-upgrade]'))b.onclick=()=>NSCampaign.advance(b.dataset.upgrade);$('repairChoice').onclick=()=>NSCampaign.advance('repair');announce('District clear. Choose an upgrade.');}
  function result(won){const state=NSCampaign.state;bossVisibility(false);showPanel(`<p class="kicker">${won?'MIDNIGHT PROTOCOL // COMPLETE':'SIGNAL LOST // DISTRICT '+(state.district+1)}</p><h2>${won?'The city is yours.':'A blade can be reforged.'}</h2><p class="lead">${won?'Six districts liberated. The Regent is gone. Somewhere beyond the skyline, the next signal is waking.':'Your district-entry checkpoint is safe. Read the warning, find the opening, and return stronger.'}</p>${stats([[Math.floor(score).toLocaleString(),'SCORE'],[state.stats.kills,'TAKEDOWNS'],[state.stats.shards+'/18','DATA SHARDS'],[time(state.stats.time),'RUN TIME']])}<div class="actions">${won?'<button class="primary" id="newCycle">New Game +</button>':'<button class="primary" id="retryCheckpoint">Retry checkpoint</button>'}<button id="resultRecords">Records</button><button id="resultTitle">Title screen</button></div><p class="panel-note">${won?'New Game + starts a fresh campaign with stronger enemies.':'Retries restore your score, health and upgrades to the start of this district.'}</p>`);$('retryCheckpoint')?.addEventListener('click',()=>NSCampaign.resume());$('newCycle')?.addEventListener('click',()=>NSCampaign.newRun(state.difficulty,Math.min(9,state.cycle+1)));$('resultRecords').onclick=records;$('resultTitle').onclick=title;announce(won?'Campaign complete. The city is free.':'Run ended. Retry checkpoint is available.');}
  function bossVisibility(visible){$('bossHud').hidden=!visible;}
  function refresh(){
    const now=performance.now();if(now-refreshAt<100)return;refreshAt=now;
    const s=NSCampaign.state,b=NSCampaign.boss,inRun=mode!=='title';
    if(inRun){$('objective').textContent=NSCampaign.objective;$('routeProgress').style.width=(NSCampaign.progress*100)+'%';$('runClock').textContent=time(s.stats.time);$('difficultyTag').textContent=s.difficulty.toUpperCase()+(s.cycle?' +'+s.cycle:'');heartsEl.setAttribute('aria-label',`${Math.ceil(P.hp)} of ${P.maxhp} hearts`);}
    else{$('routeProgress').style.width='0%';$('runClock').textContent='00:00';}
    const visible=mode==='playing'&&b?.active&&!b.dead;bossVisibility(visible);waveEl.style.top=visible?'48px':'';
    if(visible){$('bossName').textContent=b.name.toUpperCase();$('bossPhase').textContent='PHASE '+b.phase;$('bossHealth').style.width=(b.hp/b.maxhp*100)+'%';}
    let hint='';if(mode==='playing'&&s.district===0&&s.stats.time<38){const seconds=s.stats.time;hint=seconds<9?'Move: A / D or ◀ ▶ · Hold J / B to slash':seconds<18?'Space / A: double jump · Yellow diamonds reward the high route':seconds<27?'Shift / X: dash on the ground, slam in the air':'Cut all 3 relay cores, then reach the exit →';}
    if(hint!==lastHint){$('tutorialHint').textContent=hint;$('tutorialHint').hidden=!hint;lastHint=hint;}
    $('pauseBtn').setAttribute('aria-label',mode==='paused'?'Resume game':'Pause game');
  }
  function menuItems(){return [...(modal.open?modal:panel).querySelectorAll('button:not(:disabled),select,input')].filter(el=>!el.hidden);}
  function menuMove(direction){const items=menuItems();if(!items.length)return;const current=items.indexOf(document.activeElement);items[(current+direction+items.length)%items.length].focus();}
  function menuActivate(){const el=document.activeElement;if(el?.tagName==='SELECT'){el.selectedIndex=(el.selectedIndex+1)%el.options.length;el.dispatchEvent(new Event('change'));}else if(el?.tagName==='INPUT'&&el.type==='checkbox'){el.click();}else if(menuItems().includes(el))el.click();else menuItems()[0]?.focus();}
  $('pauseBtn').onclick=togglePause;$('startBtn').onclick=togglePause;$('selectBtn').onclick=openHelp;$('helpBtn').onclick=openHelp;$('settingsBtn').onclick=openSettings;$('recordsBtn').onclick=records;$('closeModal').onclick=()=>modal.close();
  modal.addEventListener('close',()=>{clearInput();if(mode==='paused')$('resumeRun')?.focus();});
  // Give keyboard users a contained menu while an in-game panel is open.
  overlay.addEventListener('keydown',event=>{if(event.code!=='Tab'||modal.open)return;const items=menuItems();if(!items.length)return;const first=items[0],last=items[items.length-1];if(event.shiftKey&&(document.activeElement===first||document.activeElement===panel)){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}});
  applySettings();title();
  if('serviceWorker' in navigator&&location.protocol==='https:')navigator.serviceWorker.register('./sw.js',{scope:'./'}).catch(()=>{});
  return {title,pause,unpause,togglePause,hidePanel,refresh,openHelp,openSettings,records,result,districtClear,announce,toast,menuMove,menuActivate,toggleSound,achievement(id){toast('ACHIEVEMENT · '+achievements[id][0]);}};
})();
