import * as THREE from './vendor/three.module.js';
import {SIZE,TYPES,TROOPS,terrainAt,noise,footprint,occupancy,sectorAt,key,buildQuote,claimQuote} from './sim.mjs';
import {TILE,makeBuilding,makeScaffold,mergeMeshes,landscapeDecor,box,cylinder} from './models.mjs';
export class CastleScene{
 constructor(canvas){
  this.canvas=canvas;this.renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:false,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,1.75));this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;this.renderer.setClearColor('#b6c5c7');this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.25;
  this.scene=new THREE.Scene();this.scene.background=new THREE.Color('#b6c5c7');this.scene.fog=new THREE.Fog('#b6c5c7',100,200);this.camera=new THREE.OrthographicCamera(-30,30,20,-20,.1,250);this.target=new THREE.Vector3(-1.2,0,-10);this.angle=.64;this.elevation=.72;this.viewSize=window.innerWidth<760?27:22;this.cameraDistance=75;
  this.scene.add(new THREE.HemisphereLight('#f7f4da','#657157',2.15));const sun=new THREE.DirectionalLight('#fff1ce',3);sun.position.set(-25,55,15);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-55;sun.shadow.camera.right=55;sun.shadow.camera.top=55;sun.shadow.camera.bottom=-55;sun.shadow.camera.near=1;sun.shadow.camera.far=130;sun.shadow.bias=-.0006;sun.shadow.normalBias=.07;this.scene.add(sun);
  const land=new THREE.PlaneGeometry(SIZE*TILE,SIZE*TILE,SIZE,SIZE);land.rotateX(-Math.PI/2);const colors=[];const p=land.getAttribute('position');for(let i=0;i<p.count;i++){const n=noise(Math.floor(p.getX(i))+200,Math.floor(p.getZ(i))+200),c=new THREE.Color('#89945e');c.multiplyScalar(.93+n*.12);colors.push(c.r,c.g,c.b);}land.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));this.ground=new THREE.Mesh(land,new THREE.MeshStandardMaterial({vertexColors:true,roughness:1}));this.ground.receiveShadow=true;this.scene.add(this.ground);
  const riverGroup=new THREE.Group();for(let z=0;z<SIZE;z++)for(let x=0;x<SIZE;x++)if(terrainAt(x,z)==='water')box(riverGroup,(x-18+.5)*TILE,.015,(z-18+.5)*TILE,TILE+.03,.03,TILE+.03,'#60949b');this.river=mergeMeshes(riverGroup);this.river.castShadow=false;this.scene.add(this.river);
  const plane=new THREE.PlaneGeometry(SIZE*TILE+100,SIZE*TILE+100);plane.rotateX(-Math.PI/2);const distant=new THREE.Mesh(plane,new THREE.MeshStandardMaterial({color:'#a0ad8a',roughness:1}));distant.position.y=-.1;distant.receiveShadow=true;this.scene.add(distant);
  this.boundaries=new THREE.Group();this.scene.add(this.boundaries);this.grid=new THREE.GridHelper(SIZE*TILE,SIZE,'#d8d0a4','#c5c2a3');this.grid.position.y=.055;this.grid.material.transparent=true;this.grid.material.opacity=.25;this.grid.visible=false;this.scene.add(this.grid);
  this.hover=new THREE.Group();this.scene.add(this.hover);this.selection=null;this.raycaster=new THREE.Raycaster();this.ndc=new THREE.Vector2();this.proxies=[];this.revision=-1;this.mode='inspect';this.rotation=0;this.hoverTile=null;this.selectedId=null;this.lastState=null;this.people=[];this.makePeople();this.resize();
 }
 resize(){this.w=this.canvas.clientWidth||window.innerWidth;this.h=this.canvas.clientHeight||window.innerHeight;this.renderer.setSize(this.w,this.h,false);this.updateCamera();}
 updateCamera(){const aspect=this.w/this.h;this.camera.left=-this.viewSize*aspect;this.camera.right=this.viewSize*aspect;this.camera.top=this.viewSize;this.camera.bottom=-this.viewSize;this.camera.position.set(this.target.x+Math.sin(this.angle)*Math.cos(this.elevation)*this.cameraDistance,this.target.y+Math.sin(this.elevation)*this.cameraDistance,this.target.z+Math.cos(this.angle)*Math.cos(this.elevation)*this.cameraDistance);this.camera.lookAt(this.target);this.camera.updateProjectionMatrix();this.camera.updateMatrixWorld();}
 pan(dx,dy){const k=this.viewSize*2/this.h,right=new THREE.Vector3(Math.cos(this.angle),0,-Math.sin(this.angle)),forward=new THREE.Vector3(Math.sin(this.angle),0,Math.cos(this.angle));this.target.addScaledVector(right,-dx*k);this.target.addScaledVector(forward,-dy*k/Math.sin(this.elevation));this.target.x=Math.max(-48,Math.min(48,this.target.x));this.target.z=Math.max(-48,Math.min(48,this.target.z));this.updateCamera();}
 rotate(delta){this.angle+=delta;this.updateCamera();}
 tilt(delta){this.elevation=Math.max(.35,Math.min(1.15,this.elevation+delta));this.updateCamera();}
 zoom(factor){this.viewSize=Math.max(9,Math.min( 60,this.viewSize/factor));this.updateCamera();}
 recenter(){this.target.set(-1.2,0,-10);this.angle=.64;this.elevation=.72;this.viewSize=this.w<760?27:22;this.updateCamera();}
 ray(sx,sy){this.ndc.set(sx/this.w*2-1,-sy/this.h*2+1);this.raycaster.setFromCamera(this.ndc,this.camera);}
 tile(sx,sy){this.ray(sx,sy);const at=new THREE.Vector3(),plane=new THREE.Plane(new THREE.Vector3(0,1,0),0);if(!this.raycaster.ray.intersectPlane(plane,at))return null;return {x:Math.floor(at.x/TILE+18),z:Math.floor(at.z/TILE+18)};}
 pick(sx,sy){this.ray(sx,sy);return this.raycaster.intersectObjects(this.proxies,false)[0]?.object.userData.buildingId||null;}
 sync(g){
  this.lastState=g;if(g.revision===this.revision)return;this.revision=g.revision;
  for(const name of ['structures','decor'])if(this[name]){this.scene.remove(this[name]);this[name].geometry.dispose();this[name].material.dispose();}
  for(const p of this.proxies){p.geometry.dispose();p.material.dispose();}this.proxies=[];
  const root=new THREE.Group();for(const b of g.buildings){const def=TYPES[b.type],w=(b.rotation%2?def.size[1]:def.size[0])*TILE,d=(b.rotation%2?def.size[0]:def.size[1])*TILE;const o=b.constructing?makeScaffold(w,d):makeBuilding(b.type,b.level,b.rotation);o.position.set((b.x-18)*TILE+w/2,0,(b.z-18)*TILE+d/2);if(b.hp<75)o.traverse(m=>{if(m.isMesh){m.material=m.material.clone();m.material.color.multiplyScalar(.78);}});root.add(o);
   const bounds=new THREE.Box3().setFromObject(o),extent=bounds.getSize(new THREE.Vector3()),center=bounds.getCenter(new THREE.Vector3());const proxy=new THREE.Mesh(new THREE.BoxGeometry(Math.max(.2,extent.x),Math.max(.15,extent.y),Math.max(.2,extent.z)),new THREE.MeshBasicMaterial({visible:false}));proxy.position.copy(center);proxy.updateMatrixWorld();proxy.userData.buildingId=b.id;this.proxies.push(proxy);
  }this.structures=mergeMeshes(root);this.scene.add(this.structures);
  const trees=new THREE.Group();landscapeDecor(trees,g,terrainAt,noise,occupancy(g));this.decor=mergeMeshes(trees);this.scene.add(this.decor);
  while(this.boundaries.children.length){const o=this.boundaries.children[0];this.boundaries.remove(o);o.geometry.dispose();o.material.dispose();}
  const points=[];for(const s of g.claimed){const [sx,sz]=s.split(',').map(Number);for(const [dx,dz,a,b,c,d]of[[-1,0,0,0,0,9],[1,0,9,0,9,9],[0,-1,0,0,9,0],[0,1,0,9,9,9]])if(!g.claimed.includes(key(sx+dx,sz+dz))){points.push(new THREE.Vector3((sx*9+a-18)*TILE,.08,(sz*9+b-18)*TILE),new THREE.Vector3((sx*9+c-18)*TILE,.08,(sz*9+d-18)*TILE));}}
  const border=new THREE.LineSegments(new THREE.BufferGeometry().setFromPoints(points),new THREE.LineDashedMaterial({color:'#e8cb86',dashSize:.55,gapSize:.32,transparent:true,opacity:.65}));border.computeLineDistances();this.boundaries.add(border);
  this.setSelection(this.selectedId,g);this.updateHover(g);
 }
 setSelection(id,g=this.lastState){this.selectedId=id;if(this.selection){this.scene.remove(this.selection);this.selection.geometry.dispose();this.selection.material.dispose();this.selection=null;}const b=g?.buildings.find(b=>b.id===id);if(!b)return;const pts=footprint(b),xs=pts.map(p=>p[0]),zs=pts.map(p=>p[1]),w=(Math.max(...xs)-Math.min(...xs)+1)*TILE,d=(Math.max(...zs)-Math.min(...zs)+1)*TILE;const mesh=new THREE.Mesh(new THREE.PlaneGeometry(w+.15,d+.15),new THREE.MeshBasicMaterial({color:'#e7c676',transparent:true,opacity:.38,depthWrite:false}));mesh.rotation.x=-Math.PI/2;mesh.position.set((b.x-18)*TILE+w/2,.08,(b.z-18)*TILE+d/2);this.selection=mesh;this.scene.add(mesh);}
 setTool(type,rotation=0){this.mode=type;this.rotation=rotation;this.grid.visible=type!=='inspect';this.updateHover(this.lastState);}
 updateHover(g){while(this.hover.children.length){const o=this.hover.children[0];this.hover.remove(o);o.geometry?.dispose();o.material?.dispose();}if(!this.hoverTile||!g||this.mode==='inspect')return;let {x,z}=this.hoverTile,w=TILE,d=TILE,ok=true;if(this.mode==='claim'){const sx=Math.floor(x/9),sz=Math.floor(z/9);x=sx*9;z=sz*9;w=d=9*TILE;ok=claimQuote(g,sx,sz).ok;}else if(TYPES[this.mode]){const def=TYPES[this.mode];w=(this.rotation%2?def.size[1]:def.size[0])*TILE;d=(this.rotation%2?def.size[0]:def.size[1])*TILE;ok=buildQuote(g,this.mode,x,z,this.rotation).ok;}
  const m=new THREE.Mesh(new THREE.PlaneGeometry(w-.08,d-.08),new THREE.MeshBasicMaterial({color:ok?'#e7ca80':'#bc5551',transparent:true,opacity:.5,depthWrite:false}));m.rotation.x=-Math.PI/2;m.position.set((x-18)*TILE+w/2,.1,(z-18)*TILE+d/2);this.hover.add(m);
  if(TYPES[this.mode]){const edges=new THREE.EdgesGeometry(new THREE.BoxGeometry(w-.15,1.2,d-.15));const box=new THREE.LineSegments(edges,new THREE.LineBasicMaterial({color:ok?'#f4d991':'#e57564',transparent:true,opacity:.7}));box.position.set(m.position.x,.6,m.position.z);this.hover.add(box);}
 }
 makePeople(){const bodyGeo=new THREE.CylinderGeometry(.11,.15,.43,5),headGeo=new THREE.IcosahedronGeometry(.105,1);this.bodies=new THREE.InstancedMesh(bodyGeo,new THREE.MeshStandardMaterial({color:'#ffffff'}),40);this.heads=new THREE.InstancedMesh(headGeo,new THREE.MeshStandardMaterial({color:'#cba982'}),40);this.bodies.castShadow=true;this.heads.castShadow=true;for(let i=0;i<40;i++){this.bodies.setColorAt(i,new THREE.Color(['#725547','#637c87','#a09162','#7b8a69','#8e5252'][i%5]));}this.scene.add(this.bodies,this.heads);this.personDummy=new THREE.Object3D();}
 animate(t,g){const count=Math.min(40,g.population),o=this.personDummy;this.bodies.count=count;this.heads.count=count;for(let i=0;i<count;i++){const n=noise(i,71),a=t*(.12+n*.12)+n*8;let x,z;if(i%3===0){x=(-.4+Math.sin(a)*4);z=-8.5+Math.cos(a)*1.4;}else if(i%3===1){x=-5.4+Math.sin(a)*1.5;z=-13+Math.cos(a)*4;}else{x=4.5+Math.sin(a)*1.4;z=-12+Math.cos(a)*3.2;}o.position.set(x,.24+Math.sin(t*6+i)*.015,z);o.rotation.y=a;o.updateMatrix();this.bodies.setMatrixAt(i,o.matrix);o.position.y=.55;o.updateMatrix();this.heads.setMatrixAt(i,o.matrix);}this.bodies.instanceMatrix.needsUpdate=true;this.heads.instanceMatrix.needsUpdate=true;}
 render(t,g){this.animate(t,g);this.renderer.render(this.scene,this.camera);}
}
