export const SIZE=36,SECTOR=9,DAY_SECONDS=20;
export const RESOURCES=['wood','stone','iron','food','gold'];
export const ROLES={builders:{name:'Builders',icon:'hammer',desc:'Share their work across the first construction order.'},farmers:{name:'Farmers',icon:'wheat',desc:'Grow food. Harvests fall in winter.'},woodcutters:{name:'Woodcutters',icon:'trees',desc:'Produce timber at lumber camps.'},quarriers:{name:'Quarry workers',icon:'mountain',desc:'Cut stone for buildings and fortifications.'},miners:{name:'Iron miners',icon:'pickaxe',desc:'Produce iron for weapons and heavy construction.'},smiths:{name:'Blacksmiths',icon:'anvil',desc:'Convert timber and iron into trade income and better military readiness.'},healers:{name:'Healers',icon:'heart-pulse',desc:'Provide healthcare for residents.'}};
export const TYPES={
 keep:{name:'Great keep',category:'castle',size:[3,3],cost:{wood:200,stone:220,gold:120},work:32,housing:12,defense:20,max:3,icon:'castle',desc:'The seat of your realm. Upgrades unlock advanced structures and expand housing.'},
 cottage:{name:'Cottage',category:'people',size:[1,1],cost:{wood:35,stone:10},work:5,housing:8,max:3,icon:'house',desc:'Shelter for eight people per level. Residents move in when food and welfare are secure.'},
 manor:{name:'Townhouse',category:'people',size:[2,1],cost:{wood:80,stone:90,gold:35},work:12,housing:24,requires:2,max:3,icon:'building-2',desc:'Denser housing for a growing castle town.'},
 farm:{name:'Farmstead',category:'production',size:[2,2],cost:{wood:45,stone:10},work:8,job:'farmers',capacity:8,max:3,icon:'wheat',desc:'Eight farming jobs per level. Each farmer produces 3.8 food per day before seasonal and morale effects.'},
 lumber:{name:'Lumber camp',category:'production',size:[2,2],cost:{wood:35,stone:10},work:6,job:'woodcutters',capacity:8,max:3,icon:'trees',desc:'Eight forestry jobs per level. Each worker produces 3 timber per day.'},
 quarry:{name:'Stone quarry',category:'production',size:[2,2],cost:{wood:60,stone:15},work:10,job:'quarriers',capacity:8,max:3,icon:'mountain',desc:'Eight quarry jobs per level. Each worker cuts 2.6 stone per day.'},
 mine:{name:'Iron mine',category:'production',size:[2,2],cost:{wood:75,stone:55,gold:25},work:12,job:'miners',capacity:6,max:3,icon:'pickaxe',desc:'Six mining jobs per level. Each miner produces 1.5 iron per day.'},
 smithy:{name:'Smithy',category:'production',size:[1,1],cost:{wood:45,stone:45,iron:10},work:9,job:'smiths',capacity:4,max:3,icon:'anvil',desc:'Each smith turns 0.5 iron and 0.5 timber into 3 gold per day. Staffed smithies improve army strength.'},
 granary:{name:'Granary',category:'production',size:[2,1],cost:{wood:60,stone:25},work:8,storage:350,max:3,icon:'warehouse',desc:'Adds 350 food storage per level. Other stockpiles also gain 150 capacity.'},
 market:{name:'Trading post',category:'production',size:[2,1],cost:{wood:65,stone:35,gold:30},work:10,max:2,icon:'store',desc:'Enables buying and selling supplies. A completed trading post improves morale.'},
 well:{name:'Village well',category:'people',size:[1,1],cost:{wood:15,stone:35},work:5,water:50,max:3,icon:'droplets',desc:'Fresh water for 50 people per level. Water and sanitation support health.'},
 infirmary:{name:'Infirmary',category:'people',size:[2,1],cost:{wood:60,stone:35,gold:30},work:9,job:'healers',capacity:4,max:3,icon:'heart-pulse',desc:'Each assigned healer cares for 20 residents. Staffing is managed in People.'},
 chapel:{name:'Chapel',category:'people',size:[2,2],cost:{wood:60,stone:100,gold:45},work:14,max:2,icon:'church',desc:'Provides community support, adding up to 10 morale.'},
 garden:{name:'Kitchen garden',category:'people',size:[1,1],cost:{wood:15,stone:5},work:3,max:2,icon:'flower-2',desc:'A little food and a place to rest. Provides 1 food per day per level and improves morale.'},
 road:{name:'Stone path',category:'castle',size:[1,1],cost:{stone:2},work:.2,max:1,icon:'route',desc:'Connect and arrange the castle grounds. Paths are decorative in this prototype.'},
 wall:{name:'Curtain wall',category:'defense',size:[1,1],cost:{stone:18,wood:4},work:2,defense:1.3,max:3,icon:'brick-wall',desc:'A solid stone perimeter. Continuous walls, gates, and towers enclose and protect the bailey.'},
 palisade:{name:'Palisade',category:'defense',size:[1,1],cost:{wood:14},work:1.5,defense:.7,max:2,icon:'fence',desc:'A quick timber perimeter. Can enclose land, but provides less defense than stone.'},
 tower:{name:'Watchtower',category:'defense',size:[1,1],cost:{wood:25,stone:65},work:7,defense:7,max:3,icon:'castle',desc:'A fortified tower that strengthens the garrison and connects perimeter walls.'},
 gate:{name:'Gatehouse',category:'defense',size:[2,1],cost:{wood:45,stone:85,iron:10},work:10,defense:10,max:3,icon:'door-open',desc:'A defended entrance. Closed gates count as part of the perimeter.'},
 barracks:{name:'Barracks',category:'military',size:[2,1],cost:{wood:70,stone:55,gold:40},work:12,max:3,icon:'swords',desc:'Train spearmen and archers from idle residents. Each level adds one training slot.'},
 stables:{name:'Stables',category:'military',size:[2,2],cost:{wood:100,stone:65,iron:20,gold:80},work:16,requires:2,max:2,icon:'flag',desc:'Unlocks mounted cavalry for expeditions. Cavalry need more supplies.'},
 siege:{name:'Siege workshop',category:'military',size:[2,2],cost:{wood:120,stone:80,iron:50,gold:100},work:18,requires:3,max:2,icon:'crosshair',desc:'Adds siege support to expeditions, increasing offensive strength by 20% per level.'}
};
export const TROOPS={spears:{name:'Spearmen',icon:'swords',power:8,cost:{wood:6,iron:2,gold:8,food:6},time:1.2,desc:'Reliable castle guards.'},archers:{name:'Archers',icon:'crosshair',power:10,cost:{wood:12,gold:12,food:8},time:1.5,desc:'Strong ranged support.'},cavalry:{name:'Cavalry',icon:'flag',power:22,cost:{wood:10,iron:8,gold:30,food:15},time:2.5,desc:'Powerful, expensive mounted troops.'}};
export const TARGETS={escort:{name:'Escort the caravan',description:'Protect merchants along the south road.',power:26,days:2,reward:{gold:95,food:35}},bandits:{name:'Clear Blackwood camp',description:'Break up the raiders gathering in the forest.',power:60,days:3,reward:{wood:100,food:75,gold:100}},outpost:{name:'Take the old quarry',description:'Seize a fortified stone outpost in the foothills.',power:120,days:4,reward:{stone:200,iron:45,gold:160}},fortress:{name:'Siege Crowfall fort',description:'A substantial offensive against a rival stronghold.',power:230,days:6,reward:{gold:400,stone:180,iron:100}}};
export const key=(x,z)=>`${x},${z}`;
export const noise=(x,z)=>{const n=Math.sin(x*127.1+z*311.7)*43758.5453123;return n-Math.floor(n)};
export const sectorAt=(x,z)=>key(Math.floor(x/SECTOR),Math.floor(z/SECTOR));
export function terrainAt(x,z){if(x<0||z<0||x>=SIZE||z>=SIZE)return 'void';if(x>28+Math.sin(z*.23)*1.6&&x<32+Math.sin(z*.23)*1.6)return 'water';if(x>=9&&x<=26&&z>=8&&z<=18)return 'grass';const n=noise(x,z);return n<.23?'forest':n>.92?'rock':'grass';}
export function footprint(b){const d=TYPES[b.type],size=b.rotation%2?[d.size[1],d.size[0]]:d.size;const out=[];for(let a=0;a<size[0];a++)for(let c=0;c<size[1];c++)out.push([b.x+a,b.z+c]);return out;}
const complete=b=>!b.constructing&&b.hp>0;
export function createGame(){
 const g={version:1,name:'Ashenford',day:1,speed:1,resources:{wood:260,stone:240,iron:55,food:230,gold:280},population:38,morale:78,health:88,jobs:{builders:6,farmers:8,woodcutters:6,quarriers:4,miners:0,smiths:0,healers:0},army:{spears:4,archers:2,cavalry:0},buildings:[],claimed:['1,1','2,1'],queue:[],training:[],expeditions:[],policies:{tax:'fair',rations:'normal'},nextRaid:12,raidCount:0,raidsWon:0,missionsWon:0,lastImmigration:1,lastDay:1,nextId:1,revision:1,logs:[],unlocks:[]};
 function b(type,x,z,rotation=0){g.buildings.push({id:'b'+g.nextId++,type,x,z,rotation,level:1,hp:100,constructing:false});}
 b('keep',16,10);for(const p of[[14,11],[14,13],[19,13],[20,10]])b('cottage',...p);b('well',16,14);b('smithy',20,12);b('barracks',20,14);b('farm',10,13);b('lumber',10,10);b('quarry',24,10);b('granary',24,14);
 for(const p of[[13,9],[22,9],[13,16],[22,16]])b('tower',...p);
 for(let x=14;x<=21;x++)b('wall',x,9);for(let z=10;z<=15;z++){b('wall',13,z,1);b('wall',22,z,1);}for(const x of[14,15,16,19,20,21])b('wall',x,16);b('gate',17,16);
 log(g,'Your charter begins. Care for 38 people and prepare the castle before day 12.','crown');return g;
}
export function log(g,text,icon='scroll-text'){g.logs.unshift({day:Math.floor(g.day),text,icon});g.logs=g.logs.slice(0,40);}
export function occupancy(g){const m=new Map();for(const b of g.buildings)for(const [x,z]of footprint(b))m.set(key(x,z),b);return m;}
export function enclosure(g){
 const blocked=new Set();for(const b of g.buildings)if(complete(b)&&['wall','palisade','tower','gate'].includes(b.type))for(const [x,z]of footprint(b))blocked.add(key(x,z));
 const outside=new Set(),q=[];for(let i=0;i<SIZE;i++){q.push([0,i],[SIZE-1,i],[i,0],[i,SIZE-1]);}for(let i=0;i<q.length;i++){const [x,z]=q[i],k=key(x,z);if(x<0||z<0||x>=SIZE||z>=SIZE||outside.has(k)||blocked.has(k))continue;outside.add(k);q.push([x-1,z],[x+1,z],[x,z-1],[x,z+1]);}
 return new Set(g.buildings.filter(b=>complete(b)&&footprint(b).some(([x,z])=>!outside.has(key(x,z))&&!blocked.has(key(x,z)))).map(b=>b.id));
}
export function metrics(g){
 const bs=g.buildings.filter(complete),sum=(type,field)=>bs.filter(b=>b.type===type).reduce((s,b)=>s+(field?TYPES[b.type][field]||0:1)*b.level*(b.hp/100),0),keep=Math.max(1,...bs.filter(b=>b.type==='keep').map(b=>b.level));
 const caps={builders:Math.max(8,g.population),farmers:0,woodcutters:0,quarriers:0,miners:0,smiths:0,healers:0};let housing=0,water=0,structural=0;
 for(const b of bs){const d=TYPES[b.type];housing+=(d.housing||0)*b.level;water+=(d.water||0)*b.level;structural+=(d.defense||0)*b.level*b.hp/100;if(d.job)caps[d.job]+=(d.capacity||0)*b.level;}
 const totalArmy=Object.values(g.army).reduce((a,b)=>a+b,0),trainees=g.training.reduce((a,b)=>a+b.count,0),assigned=Object.values(g.jobs).reduce((a,b)=>a+b,0),idle=Math.max(0,g.population-totalArmy-trainees-assigned);
 const season=['Spring','Summer','Autumn','Winter'][Math.floor((g.day-1)/20)%4],seasonFactor={Spring:1,Summer:1.2,Autumn:1.1,Winter:.45}[season];
 const productivity=(g.morale>=65?1:g.morale>=40?.85:.65)*(g.health<45?.8:1),jobs={};for(const r of Object.keys(ROLES))jobs[r]=Math.min(g.jobs[r]||0,caps[r]);
 const ration={lean:.65,normal:1,feast:1.35}[g.policies.rations],foodUse=g.population*.65*ration,totalWoodUse=season==='Winter'?g.population*.055:0;
 const rates={wood:jobs.woodcutters*3*productivity-totalWoodUse,stone:jobs.quarriers*2.6*productivity,iron:jobs.miners*1.5*productivity,food:jobs.farmers*3.8*seasonFactor*productivity+sum('garden')-foodUse,gold:g.population*({low:.3,fair:.65,high:1}[g.policies.tax])-totalArmy*.35+3};
 const smithActive=g.resources.iron>.01&&g.resources.wood>.01?jobs.smiths:0;rates.iron-=smithActive*.5;rates.wood-=smithActive*.5;rates.gold+=smithActive*3;
 const away={spears:0,archers:0,cavalry:0};for(const e of g.expeditions)for(const t of Object.keys(TROOPS))away[t]+=e.troops[t]||0;
 const home={};let guardPower=0;for(const t of Object.keys(TROOPS)){home[t]=Math.max(0,g.army[t]-away[t]);guardPower+=home[t]*TROOPS[t].power;}
 const readiness=(.7+g.morale*.003)*(1+Math.min(.2,smithActive*.04)),protectedIds=enclosure(g),keepProtected=bs.filter(b=>b.type==='keep').some(b=>protectedIds.has(b.id));
 const defense=Math.round((structural*(keepProtected?1.2:.65)+guardPower)*readiness),raidPower=80+g.raidCount*32+Math.max(0,g.claimed.length-2)*18;
 const storage={wood:550+sum('granary')*150,stone:550+sum('granary')*150,iron:300+sum('granary')*100,food:300+sum('granary')*350,gold:99999};
 const foodDays=foodUse>0?g.resources.food/foodUse:99,care=jobs.healers*20,healthTarget=Math.max(20,Math.min(100,50+Math.min(1,water/Math.max(1,g.population))*22+Math.min(1,care/Math.max(1,g.population))*25+(g.resources.food>0?3:-35)));
 const moraleTarget=Math.max(10,Math.min(100,48+(g.resources.food>foodUse*2?12:g.resources.food>0?4:-25)+(housing>=g.population?8:-12)+(water>=g.population?6:-10)+(keepProtected?6:0)+Math.min(10,sum('chapel')*5)+Math.min(6,sum('garden')*2)+(sum('market')?4:0)+({low:7,fair:0,high:-12}[g.policies.tax])+({lean:-12,normal:0,feast:8}[g.policies.rations])+(g.health>=75?6:-5)));
 const trainingSlots=Math.floor(sum('barracks')),siegeBonus=1+sum('siege')*.2;
 let advice='Your realm is steady. Expand housing, train a garrison, and invest in the grounds.';
 if(jobs.builders===0&&g.queue.length)advice='Construction is paused. Assign idle residents as builders.';else if(g.resources.food<foodUse*2||rates.food<0)advice='Food reserves are falling. Assign farmers, expand farms, or reduce rations.';else if(water<g.population)advice='Your people need fresh water. Build or upgrade a well.';else if(defense<raidPower&&g.nextRaid-g.day<5)advice='The next raid is stronger than your defenses. Train troops or finish fortifications.';else if(housing<=g.population)advice='There is no spare housing. Build or upgrade cottages before welcoming more people.';else if(g.health<75)advice='Healthcare needs attention. Build an infirmary and assign healers.';
 return {bs,keep,caps,housing,water,structural,totalArmy,trainees,assigned,idle,season,seasonFactor,productivity,jobs,rates,foodUse,foodDays,home,away,readiness,protectedIds,keepProtected,defense,raidPower,storage,care,healthTarget,moraleTarget,trainingSlots,siegeBonus,advice};
}
export function canAfford(g,cost){return Object.entries(cost).every(([r,v])=>g.resources[r]+1e-6>=v)}
function pay(g,cost){for(const [r,v]of Object.entries(cost))g.resources[r]-=v;}
function credit(g,cost){const s=metrics(g);for(const [r,v]of Object.entries(cost))g.resources[r]=Math.max(0,Math.min(s.storage[r],g.resources[r]+v));}
export function buildQuote(g,type,x,z,rotation=0){
 const d=TYPES[type];if(!d||type==='keep')return {ok:false,reason:'Select a structure from the build menu.'};if(!Number.isInteger(x)||!Number.isInteger(z))return {ok:false,reason:'Select a plot on the map.'};
 const b={type,x,z,rotation},tiles=footprint(b),occ=occupancy(g);if(tiles.some(([a,c])=>a<0||c<0||a>=SIZE||c>=SIZE))return {ok:false,reason:'Build within the realm map.'};if(tiles.some(([a,c])=>!g.claimed.includes(sectorAt(a,c))))return {ok:false,reason:'Claim this territory before building here.'};if(tiles.some(([a,c])=>terrainAt(a,c)==='water'))return {ok:false,reason:'This structure needs dry land.'};if(tiles.some(([a,c])=>occ.has(key(a,c))))return {ok:false,reason:'This plot is already occupied.'};if((d.requires||1)>Math.max(1,...g.buildings.filter(b=>b.type==='keep'&&complete(b)).map(b=>b.level)))return {ok:false,reason:`Upgrade the great keep to level ${d.requires} first.`};if(!canAfford(g,d.cost))return {ok:false,reason:'You do not have enough resources.',cost:d.cost};return {ok:true,cost:{...d.cost},work:d.work};
}
export function queueBuilding(g,type,x,z,rotation=0){const q=buildQuote(g,type,x,z,rotation);if(!q.ok)return q;pay(g,q.cost);const b={id:'b'+g.nextId++,type,x,z,rotation,level:1,hp:100,constructing:true};g.buildings.push(b);g.queue.push({id:'q'+g.nextId++,kind:'build',buildingId:b.id,name:TYPES[type].name,work:q.work,progress:0,cost:q.cost});g.revision++;log(g,`${TYPES[type].name} added to the construction queue.`,'hammer');return {ok:true,id:b.id};}
export function upgradeQuote(g,id){const b=g.buildings.find(b=>b.id===id);if(!b||!complete(b))return {ok:false,reason:'Select a completed structure.'};const d=TYPES[b.type];if(b.level>=d.max)return {ok:false,reason:'This structure is at its maximum level.'};if(g.queue.some(q=>q.buildingId===id))return {ok:false,reason:'Work is already queued for this structure.'};const cost=Object.fromEntries(Object.entries(d.cost).map(([r,v])=>[r,Math.ceil(v*b.level*1.35)]));if(!canAfford(g,cost))return {ok:false,reason:'You do not have enough resources.',cost};return {ok:true,cost,work:d.work*(1+b.level*.4)};}
export function queueUpgrade(g,id){const q=upgradeQuote(g,id);if(!q.ok)return q;const b=g.buildings.find(b=>b.id===id);pay(g,q.cost);g.queue.push({id:'q'+g.nextId++,kind:'upgrade',buildingId:id,name:`${TYPES[b.type].name} · level ${b.level+1}`,work:q.work,progress:0,cost:q.cost});g.revision++;return {ok:true};}
export function queueRepair(g,id){const b=g.buildings.find(b=>b.id===id);if(!b||b.constructing||b.hp>=100)return {ok:false,reason:'This structure does not need repairs.'};if(g.queue.some(q=>q.buildingId===id))return {ok:false,reason:'Work is already queued here.'};const cost={wood:Math.ceil((100-b.hp)*.25),stone:Math.ceil((100-b.hp)*.35)};if(!canAfford(g,cost))return {ok:false,reason:'Repairs need more timber or stone.'};pay(g,cost);g.queue.push({id:'q'+g.nextId++,kind:'repair',buildingId:id,name:`Repair ${TYPES[b.type].name}`,work:Math.max(1,(100-b.hp)*.08),progress:0,cost});return {ok:true};}
export function cancelOrder(g,id){const q=g.queue.find(q=>q.id===id);if(!q)return {ok:false,reason:'Order not found.'};g.queue=g.queue.filter(x=>x.id!==id);if(q.kind==='build')g.buildings=g.buildings.filter(b=>b.id!==q.buildingId);credit(g,Object.fromEntries(Object.entries(q.cost).map(([r,n])=>[r,Math.floor(n*.75)])));g.revision++;log(g,`${q.name} canceled. 75% of paid resources returned.`);return {ok:true};}
export function prioritize(g,id){const i=g.queue.findIndex(q=>q.id===id);if(i<0)return {ok:false,reason:'Order not found.'};g.queue.unshift(g.queue.splice(i,1)[0]);return {ok:true};}
export function removeBuilding(g,id){const b=g.buildings.find(b=>b.id===id);if(!b||b.type==='keep')return {ok:false,reason:'The great keep cannot be removed.'};const qs=g.queue.filter(q=>q.buildingId===id);if(b.constructing){if(!qs[0])return {ok:false,reason:'Construction order is missing.'};return cancelOrder(g,qs[0].id);}for(const q of qs)cancelOrder(g,q.id);g.buildings=g.buildings.filter(b=>b.id!==id);credit(g,Object.fromEntries(Object.entries(TYPES[b.type].cost).map(([r,n])=>[r,Math.floor(n*.3)])));normalizeJobs(g);g.revision++;return {ok:true};}
export function assign(g,role,delta){if(!ROLES[role]||!Number.isInteger(delta))return {ok:false,reason:'Choose a valid worker role.'};const s=metrics(g),n=g.jobs[role]+delta;if(n<0)return {ok:false,reason:'No workers remain in this role.'};if(delta>0&&delta>s.idle)return {ok:false,reason:'No idle residents. Release workers from another job first.'};if(n>s.caps[role])return {ok:false,reason:'Build or upgrade a workplace to add job capacity.'};g.jobs[role]=n;return {ok:true};}
export function normalizeJobs(g){const s=metrics(g);for(const r of Object.keys(ROLES))g.jobs[r]=Math.min(g.jobs[r]||0,s.caps[r]);let excess=Object.values(g.jobs).reduce((a,b)=>a+b,0)+s.totalArmy+s.trainees-g.population;for(const r of ['smiths','miners','quarriers','woodcutters','builders','healers','farmers']){const n=Math.max(0,Math.min(g.jobs[r],excess));g.jobs[r]-=n;excess-=n;}}
export function claimQuote(g,sx,sz){const k=key(sx,sz);if(!Number.isInteger(sx)||!Number.isInteger(sz)||sx<0||sz<0||sx>=4||sz>=4)return {ok:false,reason:'Choose a territory inside the map.'};if(g.claimed.includes(k)||g.queue.some(q=>q.sector===k))return {ok:false,reason:'This territory is already claimed or being surveyed.'};if(![[sx-1,sz],[sx+1,sz],[sx,sz-1],[sx,sz+1]].some(([a,b])=>g.claimed.includes(key(a,b))))return {ok:false,reason:'Claim land bordering your existing realm.'};const extra=Math.max(0,g.claimed.length-2),cost={wood:60+extra*15,stone:35+extra*10,gold:100+extra*35};if(!canAfford(g,cost))return {ok:false,reason:'More timber, stone, and gold are needed to claim this territory.',cost};return {ok:true,cost,work:12};}
export function claim(g,sx,sz){const q=claimQuote(g,sx,sz);if(!q.ok)return q;pay(g,q.cost);g.queue.push({id:'q'+g.nextId++,kind:'claim',sector:key(sx,sz),name:'Survey and claim territory',work:q.work,progress:0,cost:q.cost});return {ok:true};}
export function train(g,type,count){if(!TROOPS[type]||!Number.isInteger(count)||count<1||count>12)return {ok:false,reason:'Select 1–12 recruits.'};const s=metrics(g);if(s.trainingSlots<=g.training.length)return {ok:false,reason:'All barracks training slots are occupied.'};if(type==='cavalry'&&!s.bs.some(b=>b.type==='stables'))return {ok:false,reason:'Build stables to train cavalry.'};if(s.idle<count)return {ok:false,reason:'Release enough workers to make room for these recruits.'};const cost=Object.fromEntries(Object.entries(TROOPS[type].cost).map(([r,v])=>[r,v*count]));if(!canAfford(g,cost))return {ok:false,reason:'You do not have enough supplies for these recruits.'};pay(g,cost);g.training.push({id:'t'+g.nextId++,type,count,progress:0,duration:TROOPS[type].time*(1+count*.18)});log(g,`${count} ${TROOPS[type].name.toLowerCase()} begin training.`,'swords');return {ok:true};}
export function expeditionQuote(g,target,troops){const d=TARGETS[target],s=metrics(g);if(!d||!troops||Object.keys(troops).some(t=>!TROOPS[t]))return {ok:false,reason:'Choose an expedition and a valid force.'};let men=0,power=0;for(const t of Object.keys(TROOPS)){const n=troops[t]||0;if(!Number.isInteger(n)||n<0||n>s.home[t])return {ok:false,reason:'Your selected force exceeds the home garrison.'};men+=n;power+=n*TROOPS[t].power;}if(!men)return {ok:false,reason:'Assign at least one soldier to the expedition.'};if(g.expeditions.length>=2)return {ok:false,reason:'Two expeditions are already in the field.'};const cost={food:Math.ceil(men*d.days*1.3),gold:men*2};if(!canAfford(g,cost))return {ok:false,reason:'More food or gold is needed to provision this expedition.',cost};power=Math.round(power*s.readiness*s.siegeBonus);const enemy=d.power+g.missionsWon*5;return {ok:true,cost,power,enemy,men,days:d.days,homeDefense:Math.round((s.structural*(s.keepProtected?1.2:.65)+Object.keys(TROOPS).reduce((a,t)=>a+(s.home[t]-(troops[t]||0))*TROOPS[t].power,0))*s.readiness)};}
export function dispatch(g,target,troops){const q=expeditionQuote(g,target,troops);if(!q.ok)return q;pay(g,q.cost);g.expeditions.push({id:'e'+g.nextId++,target,troops:{spears:0,archers:0,cavalry:0,...troops},power:q.power,enemy:q.enemy,progress:0,duration:q.days});log(g,`${q.men} troops departed: ${TARGETS[target].name}.`,'flag');return {ok:true};}
export function trade(g,resource,amount,mode){const prices={wood:2,stone:3,iron:5,food:2};if(!metrics(g).bs.some(b=>b.type==='market'))return {ok:false,reason:'Complete a trading post first.'};if(!prices[resource]||![10,25,50].includes(amount)||!['buy','sell'].includes(mode))return {ok:false,reason:'Choose a valid trade.'};if(mode==='buy'){const cost=prices[resource]*amount;if(g.resources.gold<cost)return {ok:false,reason:'Not enough gold.'};if(g.resources[resource]+amount>metrics(g).storage[resource])return {ok:false,reason:'Your storage is full.'};g.resources.gold-=cost;g.resources[resource]+=amount;}else{if(g.resources[resource]<amount)return {ok:false,reason:'Not enough goods to sell.'};g.resources[resource]-=amount;g.resources.gold+=Math.floor(prices[resource]*amount*.55);}return {ok:true};}
export function setPolicy(g,policy,value){if(policy==='tax'&&!['low','fair','high'].includes(value)||policy==='rations'&&!['lean','normal','feast'].includes(value)||!['tax','rations'].includes(policy))return {ok:false,reason:'Unknown policy.'};g.policies[policy]=value;return {ok:true};}
function raid(g){const s=metrics(g),win=s.defense>=s.raidPower;if(win){g.raidsWon++;g.morale=Math.min(100,g.morale+4);credit(g,{gold:45});log(g,`Raid repelled: defense ${s.defense} against ${s.raidPower}. The treasury receives 45 gold.`,'shield-check');}else{g.resources.food*=.78;g.resources.wood*=.8;g.resources.gold*=.88;g.morale=Math.max(10,g.morale-14);const targets=g.buildings.filter(b=>complete(b)&&b.type!=='road').sort((a,b)=>noise(a.x+g.raidCount,a.z)-noise(b.x+g.raidCount,b.z));for(const b of targets.slice(0,3))b.hp=Math.max(20,b.hp-35);g.revision++;log(g,`The raid breached the defenses (${s.defense} / ${s.raidPower}). Stores were plundered and three structures need repairs.`,'shield-alert');}g.raidCount++;g.nextRaid=g.day+12;}
function advance(g,seconds){const days=seconds/DAY_SECONDS,s=metrics(g);g.day+=days;for(const r of RESOURCES)g.resources[r]=Math.max(0,Math.min(s.storage[r],g.resources[r]+s.rates[r]*days));
 g.health=Math.max(10,Math.min(100,g.health+(s.healthTarget-g.health)*Math.min(1,days*.12)));g.morale=Math.max(5,Math.min(100,g.morale+(s.moraleTarget-g.morale)*Math.min(1,days*.15)));
 let work=s.jobs.builders*s.productivity*days;while(work>0&&g.queue.length){const q=g.queue[0],done=Math.min(work,q.work-q.progress);q.progress+=done;work-=done;if(q.progress+1e-8>=q.work){g.queue.shift();if(q.kind==='claim'){g.claimed.push(q.sector);log(g,'New territory claimed. Buildable land expanded; future raids will be stronger.','flag');}else{const b=g.buildings.find(b=>b.id===q.buildingId);if(b){if(q.kind==='build')b.constructing=false;if(q.kind==='upgrade')b.level++;if(q.kind==='repair')b.hp=100;log(g,`${q.name} completed.`,'check');}}g.revision++;}else break;}
 for(const t of g.training)t.progress+=days;for(const t of g.training.filter(t=>t.progress>=t.duration)){g.army[t.type]+=t.count;log(g,`${t.count} ${TROOPS[t.type].name.toLowerCase()} join the garrison.`,'swords');}g.training=g.training.filter(t=>t.progress<t.duration);
 for(const e of g.expeditions)e.progress+=days;for(const e of g.expeditions.filter(e=>e.progress>=e.duration)){const win=e.power>=e.enemy;let losses=0;for(const t of Object.keys(TROOPS)){const lost=Math.min(e.troops[t],Math.floor(e.troops[t]*(win?.08:.28)));g.army[t]-=lost;losses+=lost;}g.population=Math.max(1,g.population-losses);if(win){credit(g,TARGETS[e.target].reward);g.missionsWon++;g.morale=Math.min(100,g.morale+3);log(g,`${TARGETS[e.target].name}: victory. Supplies delivered${losses?`; ${losses} soldiers lost`:''}.`,'trophy');}else{g.morale=Math.max(5,g.morale-7);log(g,`${TARGETS[e.target].name}: defeated. The survivors returned; ${losses} soldiers lost.`,'flag');}}
 g.expeditions=g.expeditions.filter(e=>e.progress<e.duration);normalizeJobs(g);
 if(Math.floor(g.day)>g.lastDay){g.lastDay=Math.floor(g.day);const now=metrics(g);if(g.day-g.lastImmigration>=3&&g.morale>=65&&g.resources.food>=now.foodUse*2&&g.health>=55&&g.population<now.housing){const n=Math.min(2,now.housing-g.population);g.population+=n;g.lastImmigration=g.day;log(g,`${n} new residents arrived. Assign their jobs in People.`,'users-round');}}
 if(g.day>=g.nextRaid)raid(g);
}

export function step(g,seconds){if(!Number.isFinite(seconds)||seconds<=0)return;let remaining=seconds;while(remaining>1e-8){const slice=Math.min(5,remaining);advance(g,slice);remaining-=slice;}}
export function restore(raw){
 if(!raw||raw.version!==1||!raw.resources||!Array.isArray(raw.buildings)||!Array.isArray(raw.queue)||!Array.isArray(raw.claimed)||!Array.isArray(raw.training)||!Array.isArray(raw.expeditions))throw Error('Invalid Kingdom Maker save.');
 for(const r of RESOURCES)if(!Number.isFinite(raw.resources[r])||raw.resources[r]<0||raw.resources[r]>1e9)throw Error('Invalid resource values.');
 for(const n of ['day','population','morale','health','nextRaid','raidCount','nextId','raidsWon','missionsWon','lastImmigration','lastDay','revision'])if(!Number.isFinite(raw[n])||raw[n]<0||raw[n]>1e9)throw Error('Invalid realm values.');
 if(!Number.isInteger(raw.population)||raw.buildings.length>SIZE*SIZE||raw.queue.length>1500||raw.claimed.some(s=>!/^([0-3]),([0-3])$/.test(s)))throw Error('Invalid map data.');
 const occupied=new Set(),ids=new Set();let keeps=0;
 for(const b of raw.buildings){if(!b||!TYPES[b.type]||typeof b.id!=='string'||!/^b\d+$/.test(b.id)||ids.has(b.id)||!Number.isInteger(b.x)||!Number.isInteger(b.z)||!Number.isInteger(b.rotation)||b.rotation<0||b.rotation>3||!Number.isInteger(b.level)||b.level<1||b.level>TYPES[b.type].max||!Number.isFinite(b.hp)||b.hp<0||b.hp>100)throw Error('Invalid structure data.');if(b.type==='keep')keeps++;ids.add(b.id);for(const [x,z]of footprint(b)){if(x<0||z<0||x>=SIZE||z>=SIZE||occupied.has(key(x,z)))throw Error('Overlapping structures in save.');occupied.add(key(x,z));}}
 if(keeps!==1)throw Error('Save must contain one great keep.');for(const r of Object.keys(ROLES))if(!Number.isInteger(raw.jobs?.[r])||raw.jobs[r]<0)throw Error('Invalid staffing.');for(const t of Object.keys(TROOPS))if(!Number.isInteger(raw.army?.[t])||raw.army[t]<0)throw Error('Invalid army.');
 for(const q of raw.queue)if(!['build','upgrade','repair','claim'].includes(q.kind)||!Number.isFinite(q.work)||q.work<=0||!Number.isFinite(q.progress)||q.progress<0||q.progress>q.work||!q.cost||Object.entries(q.cost).some(([r,v])=>!RESOURCES.includes(r)||!Number.isFinite(v)||v<0)||q.kind!=='claim'&&!ids.has(q.buildingId)||q.kind==='claim'&&!/^([0-3]),([0-3])$/.test(q.sector))throw Error('Invalid construction queue.');
 for(const t of raw.training)if(!TROOPS[t.type]||!Number.isInteger(t.count)||t.count<1||!Number.isFinite(t.progress)||t.progress<0||!Number.isFinite(t.duration)||t.duration<=0)throw Error('Invalid training.');
 for(const e of raw.expeditions)if(!TARGETS[e.target]||!e.troops||Object.keys(TROOPS).some(t=>!Number.isInteger(e.troops[t])||e.troops[t]<0)||!Number.isFinite(e.power)||!Number.isFinite(e.enemy)||!Number.isFinite(e.duration)||e.duration<=0||!Number.isFinite(e.progress)||e.progress<0)throw Error('Invalid expedition.');
 if(!['low','fair','high'].includes(raw.policies?.tax)||!['lean','normal','feast'].includes(raw.policies?.rations))throw Error('Invalid policies.');

 const armyCount=Object.values(raw.army).reduce((a,b)=>a+b,0),trainingCount=raw.training.reduce((a,b)=>a+b.count,0);
 if(armyCount+trainingCount>raw.population)throw Error('Military population exceeds the population.');
 for(const t of Object.keys(TROOPS))if(raw.expeditions.reduce((a,e)=>a+e.troops[t],0)>raw.army[t])throw Error('More deployed troops than soldiers.');
 const allIds=[...raw.buildings,...raw.queue,...raw.training,...raw.expeditions].map(v=>v.id);
 if(allIds.some(id=>typeof id!=='string'||! /^[bqte]\d+$/.test(id))||new Set(allIds).size!==allIds.length)throw Error('Invalid or duplicate record identifiers.');
 const seenOrders=new Set(),claimSectors=new Set();
 for(const q of raw.queue){if(q.kind==='claim'){if(raw.claimed.includes(q.sector)||claimSectors.has(q.sector))throw Error('Duplicate territory claim.');claimSectors.add(q.sector);continue;}
  const b=raw.buildings.find(b=>b.id===q.buildingId);if(seenOrders.has(b.id)||q.kind==='build'&&!b.constructing||q.kind!=='build'&&b.constructing||q.kind==='upgrade'&&b.level>=TYPES[b.type].max)throw Error('Invalid construction order.');seenOrders.add(b.id);}
 for(const b of raw.buildings)if(b.constructing&&!raw.queue.some(q=>q.kind==='build'&&q.buildingId===b.id))throw Error('Missing construction order.');
 for(const k of ['population','raidCount','raidsWon','missionsWon','lastDay','nextId','revision'])if(!Number.isInteger(raw[k]))throw Error('Invalid progress counter.');
 if(raw.morale>100||raw.health>100)throw Error('Invalid welfare values.');
 const safeNextId=Math.max(raw.nextId,1,...allIds.map(id=>Number(id.slice(1))+1));
 const g={...createGame(),...raw,name:typeof raw.name==='string'?raw.name.slice(0,32):'Ashenford',speed:0,nextId:safeNextId,logs:Array.isArray(raw.logs)?raw.logs.filter(l=>l&&typeof l.text==='string').slice(0,40):[]};normalizeJobs(g);return g;
}
